select PROCOD,PRODES,PROCODBAR1,PROCODBAR2,PROCODBAR3,PROCODBAR4 from TBS010 nolock where PROCODBAR1=PROCOD or PROCODBAR2=PROCOD or PROCODBAR3=PROCOD or PROCODBAR4=PROCOD

-- barras 1
select PROCOD,PRODES,PROCODBAR1 from TBS010 nolock where PROCODBAR1=PROCOD

begin tran
update TBS010 set PROCODBAR1='' where PROCODBAR1=PROCOD
commit tran

-- barras 2
select PROCOD,PRODES,PROCODBAR2 from TBS010 nolock where PROCODBAR2=PROCOD

select PROCOD,PRODES,PROCODBAR1,PROCODBAR2,PROCODBAR3,PROCODBAR4 from TBS010 nolock where PROCODBAR1<>'' and (PROCODBAR1=PROCODBAR2 or PROCODBAR1=PROCODBAR3 or PROCODBAR1=PROCODBAR4)

-- barras 3
select PROCOD,PRODES,PROCODBAR3 from TBS010 nolock where PROCODBAR3=PROCOD

select PROCOD,PRODES,PROCODBAR1,PROCODBAR2,PROCODBAR3,PROCODBAR4 from TBS010 nolock where PROCODBAR2<>'' and (PROCODBAR2=PROCODBAR3 or PROCODBAR2=PROCODBAR4)

-- barras 4
select PROCOD,PRODES,PROCODBAR4 from TBS010 nolock where PROCODBAR4=PROCOD

select PROCOD,PRODES,PROCODBAR1,PROCODBAR2,PROCODBAR3,PROCODBAR4 from TBS010 nolock where PROCODBAR3<>'' and PROCODBAR3=PROCODBAR4



