update TBS0921 set NCMUFORI='' where NCMUFORI is null

ALTER TABLE [TBS0921]
ADD [NCMUFORI] CHAR(90)     NOT NULL CONSTRAINT NCMUFORITBS0921_DEFAULT DEFAULT ''

 
 

ALTER TABLE [TBS0921]
DROP CONSTRAINT NCMUFORITBS0921_DEFAULT

select * from TBS0921 with (nolock)

ALTER TABLE [TBS0921]
ALTER COLUMN [NCMUFORI] CHAR(90) NULL

select top 1 *
  from TBS059 with (nolock)
