-- endereco de entrega
select CLICOD,ENDCOD,* from TBS002,TBS003 where CLIEMPCOD=ENDEMPCOD and CLICOD=ENDCOD and ENDTIP=2

begin tran
update TBS002
   set CLIUFEENT=TBS003.UFESIG,CLIFAXENT=ENDFAX,CLITELENT=ENDTEL,CLICEPENT=ENDCEP,CLICIDENT=ENDCID,CLIBAIENT=ENDBAI,
       CLIENDENT=ENDEND
  from TBS002,TBS003 where CLIEMPCOD=ENDEMPCOD and CLICOD=ENDCOD and ENDTIP=2
commit tran

-- endereco de cobranca
select CLICOD,ENDCOD,* from TBS002,TBS003 where CLIEMPCOD=ENDEMPCOD and CLICOD=ENDCOD and ENDTIP=1

begin tran
update TBS002
   set CLIUFECOB=TBS003.UFESIG,CLIFAXCOB=ENDFAX,CLITELCOB=ENDTEL,CLICEPCOB=ENDCEP,CLICIDCOB=ENDCID,CLIBAICOB=ENDBAI,
       CLIENDCOB=ENDEND
  from TBS002,TBS003 where CLIEMPCOD=ENDEMPCOD and CLICOD=ENDCOD and ENDTIP=1
commit tran

begin tran
update TBS002 set CLIUFEENT='',CLIFAXENT='',CLITELENT='',CLICEPENT='',CLICIDENT='',CLIBAIENT='',CLIENDENT=''
 where CLIENDENT is null
commit tran

begin tran
update TBS002 set CLIUFECOB='',CLIFAXCOB='',CLITELCOB='',CLICEPCOB='',CLICIDCOB='',CLIBAICOB='',CLIENDCOB=''
 where CLIENDCOB is null
