delete TBS005
delete TBS007
delete TBS013
delete TBS0131
delete TBS026
delete TBS0261
delete TBS037
delete TBS0371
delete TBS045
delete TBS0451
delete TBS049
delete TBS057
delete TBS062

-- importa clientes
delete TBS002
insert into TBS002 select * from SACMISAS.dbo.TBS002

-- importa clientes
delete TBS004
--insert into TBS004 select * from SACMISAS.dbo.TBS004

-- centro custo
delete TBS036
insert into TBS036 select * from SACMISAS.dbo.TBS036

-- requisitantes
delete TBS047
insert into TBS047 select * from SACMISAS.dbo.TBS047

-- empresa
delete TBS023
insert into TBS023 select * from SACMISAS.dbo.TBS023

-- log estoque
delete TBS051

-- tipos titulos
delete TBS027
insert into TBS027 select * from SACMISAS.dbo.TBS027

-- contas a receber
drop table TBS056

CREATE TABLE [dbo].[TBS056] (
  [CREEMPCOD] smallint CONSTRAINT [DF_TBS056_CREEMPCOD] DEFAULT 0 NOT NULL,
  [PFXEMPCOD] smallint CONSTRAINT [DF_TBS056_PFXEMPCOD] DEFAULT 0 NOT NULL,
  [CLIEMPCOD] smallint CONSTRAINT [DF_TBS056_CLIEMPCOD] DEFAULT 0 NOT NULL,
  [PFXCOD] char(3) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_PFXCOD] DEFAULT '' NOT NULL,
  [CRETIT] int CONSTRAINT [DF_TBS056_CRETIT] DEFAULT 0 NOT NULL,
  [CREPAR] char(2) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CREPAR] DEFAULT '' NOT NULL,
  [CLICOD] int CONSTRAINT [DF_TBS056_CLICOD] DEFAULT 0 NOT NULL,
  [TPTEMPCOD] smallint CONSTRAINT [DF_TBS056_TPTEMPCOD] DEFAULT 0,
  [TPTCOD] char(3) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_TPTCOD] DEFAULT '',
  [POREMPCOD] smallint CONSTRAINT [DF_TBS056_POREMPCOD] DEFAULT 0,
  [PORCOD] smallint CONSTRAINT [DF_TBS056_PORCOD] DEFAULT 0,
  [CREDATEMI] datetime CONSTRAINT [DF_TBS056_CREDATEMI] DEFAULT '17530101',
  [CREDATVEN] datetime CONSTRAINT [DF_TBS056_CREDATVEN] DEFAULT '17530101',
  [CREDATVENREA] datetime CONSTRAINT [DF_TBS056_CREDATVENREA] DEFAULT '17530101',
  [CREVAL] money CONSTRAINT [DF_TBS056_CREVAL] DEFAULT 0,
  [CREVALRES] money CONSTRAINT [DF_TBS056_CREVALRES] DEFAULT 0,
  [CREVALABT] money CONSTRAINT [DF_TBS056_CREVALABT] DEFAULT 0,
  [CRETIPDED] smallint CONSTRAINT [DF_TBS056_CRETIPDED] DEFAULT 0,
  [CREVALACR] money CONSTRAINT [DF_TBS056_CREVALACR] DEFAULT 0,
  [CRETIPACR] smallint CONSTRAINT [DF_TBS056_CRETIPACR] DEFAULT 0,
  [CREVALREC] money CONSTRAINT [DF_TBS056_CREVALREC] DEFAULT 0,
  [CREDATBAI] datetime CONSTRAINT [DF_TBS056_CREDATBAI] DEFAULT '17530101',
  [CREOBS] char(254) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CREOBS] DEFAULT '',
  [CRESTATUS] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CRESTATUS] DEFAULT '',
  [CREFATURA] char(6) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CREFATURA] DEFAULT '',
  [CREPFXFAT] char(3) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CREPFXFAT] DEFAULT '',
  [CRETITFAT] smallint CONSTRAINT [DF_TBS056_CRETITFAT] DEFAULT 0,
  [CRENUMBOR] int CONSTRAINT [DF_TBS056_CRENUMBOR] DEFAULT 0,
  [CREDATBOR] datetime CONSTRAINT [DF_TBS056_CREDATBOR] DEFAULT '17530101',
  [CRESEL] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CRESEL] DEFAULT '',
  [CREIMPBOLRES] char(45) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CREIMPBOLRES] DEFAULT '',
  [CRETITORI] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CRETITORI] DEFAULT '',
  [CLINOM] char(50) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS056_CLINOM] DEFAULT '',
  [CRENUMBAN] char(12) COLLATE Latin1_General_BIN DEFAULT ''
)
ON [PRIMARY]

CREATE NONCLUSTERED INDEX [ITBS0561] ON [dbo].[TBS056]
  ([POREMPCOD], [PORCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0562] ON [dbo].[TBS056]
  ([TPTEMPCOD], [TPTCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0563] ON [dbo].[TBS056]
  ([CLIEMPCOD], [CLICOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0564] ON [dbo].[TBS056]
  ([PFXEMPCOD], [PFXCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0565] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CRENUMBOR])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0566] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CLICOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0567] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CLINOM])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0568] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CREDATEMI])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0569] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [PORCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS056B] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CRETIT])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS056C] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CREDATVEN])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS056D] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CREDATVENREA])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS056E] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CREPFXFAT], [CREFATURA])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS056F] ON [dbo].[TBS056]
  ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [CREVAL])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS056G] ON [dbo].[TBS056]
  ([CREEMPCOD], [CRENUMBAN])
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBS056]
ADD PRIMARY KEY CLUSTERED ([CREEMPCOD], [PFXEMPCOD], [CLIEMPCOD], [PFXCOD], [CRETIT], [CREPAR], [CLICOD])
ON [PRIMARY]
GO

insert into TBS056 select * from SACMISAS.dbo.TBS056

-- historico contas a receber
delete TBS060
insert into TBS060 select * from SACMISAS.dbo.TBS060

-- prefixo contas receber/pagar
delete TBS061
insert into TBS061 select * from SACMISAS.dbo.TBS061

-- portador contas receber/pagar
delete TBS063
insert into TBS063 select * from SACMISAS.dbo.TBS063

-- propects
delete TBS038
insert into TBS038 select * from SACMISAS.dbo.TBS038

-- orcamentos
drop table TBS043

CREATE TABLE [dbo].[TBS043] (
  [ORCEMPCOD] smallint CONSTRAINT [DF_TBS043_ORCEMPCOD] DEFAULT 0 NOT NULL,
  [ORCNUM] int CONSTRAINT [DF_TBS043_ORCNUM] DEFAULT 0 NOT NULL,
  [ORCDATCAD] datetime CONSTRAINT [DF_TBS043_ORCDATCAD] DEFAULT '17530101',
  [ORCPARA] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCPARA] DEFAULT '',
  [ORCCLI] int CONSTRAINT [DF_TBS043_ORCCLI] DEFAULT 0,
  [ORCCLIEMP] smallint CONSTRAINT [DF_TBS043_ORCCLIEMP] DEFAULT 0,
  [ORCNOM] char(50) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCNOM] DEFAULT '',
  [VENCOD] smallint CONSTRAINT [DF_TBS043_VENCOD] DEFAULT 0,
  [VENEMPCOD] smallint CONSTRAINT [DF_TBS043_VENEMPCOD] DEFAULT 0,
  [ORCVENCOM] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCVENCOM] DEFAULT '',
  [ORCVENPDC] smallmoney CONSTRAINT [DF_TBS043_ORCVENPDC] DEFAULT 0,
  [ORCOBS] char(254) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCOBS] DEFAULT '',
  [TRNCOD] int CONSTRAINT [DF_TBS043_TRNCOD] DEFAULT 0,
  [TRNEMPCOD] smallint CONSTRAINT [DF_TBS043_TRNEMPCOD] DEFAULT 0,
  [ORCPESBRU] smallmoney CONSTRAINT [DF_TBS043_ORCPESBRU] DEFAULT 0,
  [ORCPESLIQ] smallmoney CONSTRAINT [DF_TBS043_ORCPESLIQ] DEFAULT 0,
  [ORCVOLQTD] int CONSTRAINT [DF_TBS043_ORCVOLQTD] DEFAULT 0,
  [ORCVOLESP] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCVOLESP] DEFAULT '',
  [ORCVOLMAR] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCVOLMAR] DEFAULT '',
  [ORCVOLNUM] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCVOLNUM] DEFAULT '',
  [ORCULTITE] smallint CONSTRAINT [DF_TBS043_ORCULTITE] DEFAULT 0,
  [CPGCOD] smallint CONSTRAINT [DF_TBS043_CPGCOD] DEFAULT 0,
  [CPGEMPCOD] smallint CONSTRAINT [DF_TBS043_CPGEMPCOD] DEFAULT 0,
  [ORCCPGDUP] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCCPGDUP] DEFAULT '',
  [ORCREQEMP] smallint CONSTRAINT [DF_TBS043_ORCREQEMP] DEFAULT 0,
  [ORCREQCOD] smallint CONSTRAINT [DF_TBS043_ORCREQCOD] DEFAULT 0,
  [ORCREQNOM] char(35) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCREQNOM] DEFAULT '',
  [ORCREQCDC] char(15) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCREQCDC] DEFAULT '',
  [ORCPEDCLI] char(15) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCPEDCLI] DEFAULT '',
  [ORCDESICMS] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCDESICMS] DEFAULT '',
  [ORCTIPFRE] smallint CONSTRAINT [DF_TBS043_ORCTIPFRE] DEFAULT 0,
  [ORCPDVNUM] int CONSTRAINT [DF_TBS043_ORCPDVNUM] DEFAULT 0,
  [ORCPDVDAT] datetime CONSTRAINT [DF_TBS043_ORCPDVDAT] DEFAULT '17530101',
  [ORCBLQCRE] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCBLQCRE] DEFAULT '',
  [ORCVALPRO] smallint CONSTRAINT [DF_TBS043_ORCVALPRO] DEFAULT 0,
  [ORCPRAENT] smallint CONSTRAINT [DF_TBS043_ORCPRAENT] DEFAULT 0,
  [ORCESTDES] char(2) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCESTDES] DEFAULT '',
  [ORCUSUCRE] char(45) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCUSUCRE] DEFAULT '',
  [ORCTIPENT] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS043_ORCTIPENT] DEFAULT '',
  [ORCPDDTOT] decimal(8, 5) CONSTRAINT [DF_TBS043_ORCPDDTOT] DEFAULT 0,
  [ORCVALFRE] money CONSTRAINT [DF_TBS043_ORCVALFRE] DEFAULT 0,
  [ORCVALSEG] money CONSTRAINT [DF_TBS043_ORCVALSEG] DEFAULT 0,
  [ORCVALDES] money CONSTRAINT [DF_TBS043_ORCVALDES] DEFAULT 0,
  [ORCVDDTOT] money DEFAULT 0
)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0431] ON [dbo].[TBS043]
  ([CPGEMPCOD], [CPGCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0432] ON [dbo].[TBS043]
  ([TRNEMPCOD], [TRNCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0433] ON [dbo].[TBS043]
  ([VENEMPCOD], [VENCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0434] ON [dbo].[TBS043]
  ([ORCEMPCOD], [ORCDATCAD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0435] ON [dbo].[TBS043]
  ([ORCEMPCOD], [ORCCLI])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0436] ON [dbo].[TBS043]
  ([ORCEMPCOD], [ORCNOM])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0437] ON [dbo].[TBS043]
  ([ORCEMPCOD], [ORCPARA])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0438] ON [dbo].[TBS043]
  ([ORCEMPCOD], [VENCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0439] ON [dbo].[TBS043]
  ([ORCEMPCOD], [ORCPDVNUM])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS043A] ON [dbo].[TBS043]
  ([ORCEMPCOD], [ORCNUM] DESC)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBS043]
ADD PRIMARY KEY CLUSTERED ([ORCEMPCOD], [ORCNUM])
ON [PRIMARY]
GO

insert into TBS043 select * from SACMISAS.dbo.TBS043

-- excluir colunca ORCPDDTOT

-- itens orcamentos
delete TBS0431
insert into TBS0431 select * from SACMISAS.dbo.TBS0431

-- bloqueio credito/precos
delete TBS053
insert into TBS053 select * from SACMISAS.dbo.TBS053

-- pedidos vendas
drop table TBS055

CREATE TABLE [dbo].[TBS055] (
  [PDVEMPCOD] smallint CONSTRAINT [DF_TBS055_PDVEMPCOD] DEFAULT 0 NOT NULL,
  [PDVNUM] int CONSTRAINT [DF_TBS055_PDVNUM] DEFAULT 0 NOT NULL,
  [PDVDATCAD] datetime CONSTRAINT [DF_TBS055_PDVDATCAD] DEFAULT '17530101',
  [PDVCLICOD] int CONSTRAINT [DF_TBS055_PDVCLICOD] DEFAULT 0,
  [PDVCLIEMP] smallint CONSTRAINT [DF_TBS055_PDVCLIEMP] DEFAULT 0,
  [PDVCLINOM] char(50) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVCLINOM] DEFAULT '',
  [VENCOD] smallint CONSTRAINT [DF_TBS055_VENCOD] DEFAULT 0,
  [VENEMPCOD] smallint CONSTRAINT [DF_TBS055_VENEMPCOD] DEFAULT 0,
  [PDVVENCOM] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVVENCOM] DEFAULT '',
  [PDVVENPDC] smallmoney CONSTRAINT [DF_TBS055_PDVVENPDC] DEFAULT 0,
  [PDVOBS] char(254) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVOBS] DEFAULT '',
  [TRNCOD] int CONSTRAINT [DF_TBS055_TRNCOD] DEFAULT 0,
  [TRNEMPCOD] smallint CONSTRAINT [DF_TBS055_TRNEMPCOD] DEFAULT 0,
  [PDVPESBRU] smallmoney CONSTRAINT [DF_TBS055_PDVPESBRU] DEFAULT 0,
  [PDVPESLIQ] smallmoney CONSTRAINT [DF_TBS055_PDVPESLIQ] DEFAULT 0,
  [PDVVOLQTD] int CONSTRAINT [DF_TBS055_PDVVOLQTD] DEFAULT 0,
  [PDVVOLESP] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVVOLESP] DEFAULT '',
  [PDVVOLMAR] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVVOLMAR] DEFAULT '',
  [PDVVOLNUM] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVVOLNUM] DEFAULT '',
  [PDVULTITE] smallint CONSTRAINT [DF_TBS055_PDVULTITE] DEFAULT 0,
  [CPGCOD] smallint CONSTRAINT [DF_TBS055_CPGCOD] DEFAULT 0,
  [CPGEMPCOD] smallint CONSTRAINT [DF_TBS055_CPGEMPCOD] DEFAULT 0,
  [PDVCPGDUP] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVCPGDUP] DEFAULT '',
  [PDVREQEMP] smallint CONSTRAINT [DF_TBS055_PDVREQEMP] DEFAULT 0,
  [PDVREQCOD] smallint CONSTRAINT [DF_TBS055_PDVREQCOD] DEFAULT 0,
  [PDVREQNOM] char(35) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVREQNOM] DEFAULT '',
  [PDVREQCDC] char(15) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVREQCDC] DEFAULT '',
  [PDVPEDCLI] char(15) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVPEDCLI] DEFAULT '',
  [PDVDESICMS] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVDESICMS] DEFAULT '',
  [PDVTIPFRE] smallint CONSTRAINT [DF_TBS055_PDVTIPFRE] DEFAULT 0,
  [PDVORCNUM] int CONSTRAINT [DF_TBS055_PDVORCNUM] DEFAULT 0,
  [PDVBLQCRE] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVBLQCRE] DEFAULT '',
  [PDVVALFRE] money CONSTRAINT [DF_TBS055_PDVVALFRE] DEFAULT 0,
  [PDVVALSEG] money CONSTRAINT [DF_TBS055_PDVVALSEG] DEFAULT 0,
  [PDVVALDES] money CONSTRAINT [DF_TBS055_PDVVALDES] DEFAULT 0,
  [PDVESTDES] char(2) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVESTDES] DEFAULT '',
  [PDVNFSNUM] int CONSTRAINT [DF_TBS055_PDVNFSNUM] DEFAULT 0,
  [PDVUSUCRE] char(45) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVUSUCRE] DEFAULT '',
  [PDVTRAPRO] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVTRAPRO] DEFAULT '',
  [PDVTIPENT] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS055_PDVTIPENT] DEFAULT '',
  [PDVVDDTOT] money DEFAULT 0
)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0551] ON [dbo].[TBS055]
  ([CPGEMPCOD], [CPGCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0552] ON [dbo].[TBS055]
  ([TRNEMPCOD], [TRNCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0553] ON [dbo].[TBS055]
  ([VENEMPCOD], [VENCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0554] ON [dbo].[TBS055]
  ([PDVEMPCOD], [VENCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0555] ON [dbo].[TBS055]
  ([PDVEMPCOD], [PDVDATCAD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0556] ON [dbo].[TBS055]
  ([PDVEMPCOD], [PDVCLICOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0557] ON [dbo].[TBS055]
  ([PDVEMPCOD], [PDVCLINOM])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0558] ON [dbo].[TBS055]
  ([PDVEMPCOD], [PDVNUM] DESC)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0559] ON [dbo].[TBS055]
  ([PDVEMPCOD], [PDVPEDCLI])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS055A] ON [dbo].[TBS055]
  ([PDVEMPCOD], [PDVREQNOM])
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBS055]
ADD PRIMARY KEY CLUSTERED ([PDVEMPCOD], [PDVNUM])
ON [PRIMARY]
GO

insert into TBS055 select * from SACMISAS.dbo.TBS055

-- excluir colunca PDVPDDTOT

-- itens pedidos vendas
delete TBS0551
insert into TBS0551 select * from SACMISAS.dbo.TBS0551

-- notas fiscais saida
drop table TBS067

CREATE TABLE [dbo].[TBS067] (
  [NFSEMPCOD] smallint CONSTRAINT [DF_TBS067_NFSEMPCOD] DEFAULT 0 NOT NULL,
  [NFSNUM] int CONSTRAINT [DF_TBS067_NFSNUM] DEFAULT 0 NOT NULL,
  [NFSDATEMI] datetime CONSTRAINT [DF_TBS067_NFSDATEMI] DEFAULT '17530101',
  [NFSUSUGER] char(45) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSUSUGER] DEFAULT '',
  [NFSDATSAI] datetime CONSTRAINT [DF_TBS067_NFSDATSAI] DEFAULT '17530101',
  [NFSHORSAI] char(8) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSHORSAI] DEFAULT '',
  [NFSCAN] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSCAN] DEFAULT '',
  [NFSDEV] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSDEV] DEFAULT '',
  [NFSDATCAN] datetime CONSTRAINT [DF_TBS067_NFSDATCAN] DEFAULT '17530101',
  [NFSUSUCAN] char(25) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSUSUCAN] DEFAULT '',
  [SEREMPCOD] smallint CONSTRAINT [DF_TBS067_SEREMPCOD] DEFAULT 0,
  [SERCOD] char(3) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_SERCOD] DEFAULT '',
  [NFSCLIEMP] smallint CONSTRAINT [DF_TBS067_NFSCLIEMP] DEFAULT 0,
  [NFSCLICOD] int CONSTRAINT [DF_TBS067_NFSCLICOD] DEFAULT 0,
  [NFSCLINOM] char(50) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSCLINOM] DEFAULT '',
  [NFSREQCOD] smallint CONSTRAINT [DF_TBS067_NFSREQCOD] DEFAULT 0,
  [NFSREQNOM] char(35) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSREQNOM] DEFAULT '',
  [VENEMPCOD] smallint CONSTRAINT [DF_TBS067_VENEMPCOD] DEFAULT 0,
  [VENCOD] smallint CONSTRAINT [DF_TBS067_VENCOD] DEFAULT 0,
  [NFSVENCOM] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSVENCOM] DEFAULT '',
  [NFSVENPDC] smallmoney CONSTRAINT [DF_TBS067_NFSVENPDC] DEFAULT 0,
  [UFESIG] char(2) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_UFESIG] DEFAULT '',
  [CPGEMPCOD] smallint CONSTRAINT [DF_TBS067_CPGEMPCOD] DEFAULT 0,
  [CPGCOD] smallint CONSTRAINT [DF_TBS067_CPGCOD] DEFAULT 0,
  [NFSCPGDUP] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSCPGDUP] DEFAULT '',
  [TRNEMPCOD] smallint CONSTRAINT [DF_TBS067_TRNEMPCOD] DEFAULT 0,
  [TRNCOD] int CONSTRAINT [DF_TBS067_TRNCOD] DEFAULT 0,
  [NFSPRONUM] int CONSTRAINT [DF_TBS067_NFSPRONUM] DEFAULT 0,
  [NFSTIPFRE] smallint CONSTRAINT [DF_TBS067_NFSTIPFRE] DEFAULT 0,
  [NFSDESICMS] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSDESICMS] DEFAULT '',
  [NFSREQCDC] char(15) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSREQCDC] DEFAULT '',
  [NFSPEDCLI] char(15) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSPEDCLI] DEFAULT '',
  [NFSANTNUM] int CONSTRAINT [DF_TBS067_NFSANTNUM] DEFAULT 0,
  [NFSVALFRE] money CONSTRAINT [DF_TBS067_NFSVALFRE] DEFAULT 0,
  [NFSVALSEG] money CONSTRAINT [DF_TBS067_NFSVALSEG] DEFAULT 0,
  [NFSVALDES] money CONSTRAINT [DF_TBS067_NFSVALDES] DEFAULT 0,
  [NFSOBS] char(254) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSOBS] DEFAULT '',
  [NFSTIP] char(1) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSTIP] DEFAULT '',
  [NFSORINUM] int CONSTRAINT [DF_TBS067_NFSORINUM] DEFAULT 0,
  [NFSORIEMI] datetime CONSTRAINT [DF_TBS067_NFSORIEMI] DEFAULT '17530101',
  [NFSTOTOUT] money CONSTRAINT [DF_TBS067_NFSTOTOUT] DEFAULT 0,
  [NFSVOLNUM] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSVOLNUM] DEFAULT '',
  [NFSVOLMAR] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSVOLMAR] DEFAULT '',
  [NFSVOLESP] char(20) COLLATE Latin1_General_BIN CONSTRAINT [DF_TBS067_NFSVOLESP] DEFAULT '',
  [NFSVOLQTD] int CONSTRAINT [DF_TBS067_NFSVOLQTD] DEFAULT 0,
  [NFSPESLIQ] smallmoney CONSTRAINT [DF_TBS067_NFSPESLIQ] DEFAULT 0,
  [NFSPESBRU] smallmoney CONSTRAINT [DF_TBS067_NFSPESBRU] DEFAULT 0,
  [NFSCODFIS] char(5) COLLATE Latin1_General_BIN DEFAULT '',
  [NFSMESAPU] smallint DEFAULT 0,
  [NFSANOAPU] smallint DEFAULT 0,
  [NFSVDDTOT] money DEFAULT 0
)
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0671] ON [dbo].[TBS067]
  ([VENEMPCOD], [VENCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0672] ON [dbo].[TBS067]
  ([SEREMPCOD], [SERCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0673] ON [dbo].[TBS067]
  ([TRNEMPCOD], [TRNCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0674] ON [dbo].[TBS067]
  ([CPGEMPCOD], [CPGCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0675] ON [dbo].[TBS067]
  ([UFESIG])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0676] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSNUM], [NFSDATEMI])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0677] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSCAN])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0678] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSCLICOD], [NFSDATEMI])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS0679] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSDATEMI], [NFSNUM])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS067A] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSCLINOM])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS067B] ON [dbo].[TBS067]
  ([NFSEMPCOD], [VENCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS067C] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSDATEMI], [VENCOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS067D] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSDATEMI], [NFSCLICOD])
ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ITBS067E] ON [dbo].[TBS067]
  ([NFSEMPCOD], [NFSNUM] DESC)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBS067]
ADD PRIMARY KEY CLUSTERED ([NFSEMPCOD], [NFSNUM])
ON [PRIMARY]
GO

insert into TBS067 select * from SACMISAS.dbo.TBS067

-- excluir colunca NFSPDDTOT

-- posicao faturamento
delete TBS069
insert into TBS069 select * from SACMISAS.dbo.TBS069

-- atualiza codigo
   update TBS024 set TBSVALSEQ=(select max(CLICOD) from TBS002) where TBSNOM='TBS002'
   update TBS024 set TBSVALSEQ=(select max(VENCOD) from TBS004) where TBSNOM='TBS004'
   update TBS024 set TBSVALSEQ=(select max(FORCOD) from TBS006) where TBSNOM='TBS006'
   update TBS024 set TBSVALSEQ=(select max(PDCNUM) from TBS045) where TBSNOM='TBS045'
   update TBS024 set TBSVALSEQ=(select max(MVIDOC) from TBS037) where TBSNOM='TBS037'
   update TBS024 set TBSVALSEQ=(select max(MDSREG) from TBS049) where TBSNOM='TBS049'
   update TBS024 set TBSVALSEQ=(select max(PSTCOD) from TBS038) where TBSNOM='TBS038'
   update TBS024 set TBSVALSEQ=(select max(ORCNUM) from TBS043) where TBSNOM='TBS043'
   update TBS024 set TBSVALSEQ=(select max(PDVNUM) from TBS055) where TBSNOM='TBS055'

-- atualiza codigo vendedor
update TBS002 set VENCOD=999 where VENCOD=3
update TBS002 set VENCOD=3 where VENCOD=1 or VENCOD=2
update TBS002 set VENCOD=2 where VENCOD=241 or VENCOD=99
update TBS002 set VENCOD=1 where VENCOD=4
update TBS002 set VENCOD=4 where VENCOD=95
