ALTER TABLE [TBS0672]
ALTER COLUMN [NFSPDVPEDCLI] CHAR(30) NULL

ALTER TABLE [TBS067]
ALTER COLUMN [NFSPEDCLI] CHAR(30) NULL


DROP INDEX [ITBS0559] ON [TBS055]

ALTER TABLE [TBS055]
ALTER COLUMN [PDVPEDCLI] CHAR(30) NULL

CREATE NONCLUSTERED INDEX [ITBS0559] ON [TBS055] (
      [PDVEMPCOD],
      [PDVPEDCLI])

 
ALTER TABLE [TBS0431]
ADD [ORCPROGERPEN] CHAR(1)     NOT NULL CONSTRAINT ORCPROGERPENTBS0431_DEFAULT DEFAULT ''

ALTER TABLE [TBS0431]
DROP CONSTRAINT ORCPROGERPENTBS0431_DEFAULT

 
ALTER TABLE [TBS043]
ALTER COLUMN [ORCPEDCLI] CHAR(30) NULL

