select A.PROCOD,A.PRODES,A.PROCLAFIS,isnull(B.PROCLAFIS,'')
  from BESTBAG.SIBD2.dbo.TBS010 A left join PAPELYNA.SIBD.dbo.TBS010 B on A.PROEMPCOD = B.PROEMPCOD and A.PROCOD = B.PROCOD
 where A.PROCLAFIS <> B.PROCLAFIS