INSERT INTO TBS121 VALUES('\FIGURAS\', '\INTEGROS\FIGURAS\', '*.BMP', 'FIGURAS DO SISTEMA', 'N')
INSERT INTO TBS121 VALUES('\FIGURAS\', '\INTEGROS\FIGURAS\', '*.ICO', 'FIGURAS DO SISTEMA', 'N')
INSERT INTO TBS121 VALUES('\FIGURAS\', '\INTEGROS\FIGURAS\', '*.JPG', 'FIGURAS DO SISTEMA', 'N')
INSERT INTO TBS121 VALUES('\FIGURAS\', '\INTEGROS\FIGURAS\', '*.PNG', 'FIGURAS DO SISTEMA', 'N')
INSERT INTO TBS121 VALUES('\ODBC\', '\INTEGROS\ODBC\', '*.PAD', 'ARQUIVOS DE CONEXAO COM BANCO', 'N')
INSERT INTO TBS121 VALUES('\ATUAL\', '\INTEGROS\BIN\', '', 'ARQUIVOS DE APLICACAO', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'IMAGES.TXT', 'ARQUIVO DE REFERENCIA DAS IMAGENS', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'MENSAGEM_*.TXT', 'ARQUIVO DE MENSAGENS', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', '*.VCT', 'ARQUIVO DO VFP', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', '*.VCX', 'ARQUIVO DO VFP', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'CONFIG.FPW', 'ARQUIVO DO VFP', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'VFP9*.DLL', 'ARQUIVO DO VFP', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'RBUILDER.DLL', 'ARQUIVO DO VFP', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'REPORTS.DLL', 'ARQUIVO AUXILIAR FLEXDOCS', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'MICROSOFT.MSHTML.DLL', 'ARQUIVO AUXILIAR FLEXDOCS', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'SUMATRAPDF.EXE', 'ARQUIVO AUXILIAR FLEXDOCS', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'GX*.DLL', 'ARQUIVOS AUXILIARES GENEXUS', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'GXPRN.INI', 'ARQUIVOS AUXILIARES GENEXUS', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'RAR.EXE', 'ARQUIVO PARA COMPACTACAO', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'PPRINTER.EXE', 'ARQUIVO AUXILIAR PARA IMPRESSAO', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'DLLINSCE32.DLL', 'ARQUIVO PARA VALIDACAO IE', 'N')
INSERT INTO TBS121 VALUES('\', '\INTEGROS\', 'VALIDARSUFRAMA.DLL', 'ARQUIVO PARA VALIDACAO SUFRAMA', 'N')


SELECT * FROM TBS121
ORDER BY LAAORI

--DELETE TBS121



