update TBS002 set CLICID='AMPARO' where CLICID='AMPARO - SP'

update TBS002 set CLICID='APARECIDA' where CLICID in('APARECIDA DO NORTE','APARECIDA DO NORT')

update TBS002 set CLICID='APARECIDA DO TABOA' where CLICID='APARECIDA DO TABOADO'

update TBS002 set CLICID='ARACARIGUAMA'
 where CLICID in('ARACARIGUAMA CXPOSTAL121','ARARIGUAMA','ARA€ARIGUAMA','ARAÇARIGUAMA   - SÃO PAULO')

update TBS002 set CLICID='ARACARIGUAMA' where CLICID in('ARACOIABA DA SE','ARAI€OIABA SERRA','ARA€OIABA DA SERRA')

update TBS002 set CLICID='ARACATUBA' where CLICID='ARA€ATUBA'

update TBS002 set CLICID='BARUERI'
 where CLICID in('ARUERI','BABUERI','BARUERI   SAO PAULO','BARUERI  SP','BARUERI SAO PAULO','BARUERI SP','BARUERI-SP',
                 'BARUEI')

update TBS002 set CLICID='ARUJA' where CLICID='ARUJA-SAO PAULO'

update TBS002 set CLICID='OSASCO'
 where CLICID in('ASASCO','OSAACO','OSACO','OSAS CO','OSASCO  O','OSASCO - SP','OSASCO SAO PAULO','OSASCO SP',
                 'OSASCO-SP','OSASO','OSSCO','OASACO')

update TBS002 set CLICID='BELO HORIZONTE' where CLICID='BELO HORINZONTE'

update TBS002 set CLICID='BIRITIBA-MIRIM' where CLICID='BIRITIBA MIRIM'

update TBS002 set CLICID='BOTUCATU' where CLICID='BOTUCATU - CXP 059'

update TBS002 set CLICID='BRAGANCA PAULISTA'
 where CLICID in('BRAG PAULISTA','BRAGANCA PTA','BRAGAN€A PAULISTA','BREGANCA PAULISTA')

update TBS002 set CLICID='CAMPO LIMPO PAULISTA'
 where CLICID in('C LIMPO PTA.','C LIMPO-SAO PAULO','CAMPO LIMPO','CAMPO LIMPO PAULIS','CAMPO LIMPO PTA')

update TBS002 set CLICID='BRASILIA' where CLICID in('BRASILIA D.F','DISTRITO FEDERAL','DISTRITO FEDRAL')

update TBS002 set CLICID='CAMPOS DO JORDAO'
 where CLICID in('CAMP DO JORDAO','CAMPO DO JORDAO','CAMPOS','CAMPOS DE JORDAO','CAMPOS DO JORDÇO','CAMPOS JORDAO')

update TBS002 set CLICID='COTIA' where CLICID in('COTIA SAO PAULO','COTIA-SP')

update TBS002 set CLICID='CAIEIRAS' where CLICID in('CAEIRAS','CAIEIRA','CAIEIRAS]','CAIERAS')

update TBS002 set CLICID='CARAPICUIBA' where CLICID in('CARAPICUIBA SAO PAULO')

update TBS002 set CLICID='CACAPAVA' where CLICID in('CA€APAVA')

update TBS002 set CLICID='EMBU-GUACU' where CLICID in('EMBU GUACU','EMBU GUA€U','EMBU-GUA€U','EMBUGUA€U')

update TBS002 set CLICID='GUARULHOS' where CLICID in('GARULHOS','GUARULHO')

update TBS002 set CLICID='IBIUNA' where CLICID in('IBIUNA-SP')

update TBS002 set CLICID='JACAREI' where CLICID in('JACAREI-CAC CXP.33','JACAREÖ')

update TBS002 set CLICID='JUNDIAI' where CLICID in('JUNDIAI  SP','JUNDIAÖ')

update TBS002 set CLICID='PRESIDENTE PRUDENTE' where CLICID in('PRES PRUDENTE','PRES. PRUDENTE')

update TBS002 set CLICID='RIBEIRAO PRETO' where CLICID in('RIBEIRO PRETO')

update TBS002 set CLICID='RIO DE JANEIRO' where CLICID in('RIO','RIO DE DE JANEIRO','RJ')

update TBS002 set CLICID='SAO BERNARDO DO CAMPO'
 where CLICID in('SAO BERNADO DO CAMPO','SAO BERNADO DO CAMPOS','SAO BERNARDO CAMP','S B DO CAMPO','S BERNARDO CAMPO',
                 'S. BERNARDO','S. BERNARDO DO CAMPO','S.BERNARDO CAMPO','S B CAMPOS','S BERN CAMPO',
                 'S BERNADO DO CAMPO','S. B CAMPO','S. B DO CAMPO','S. B. DE CAMPO','S. B. DO CAMPO','S. B. DO CAMPOS',
                 'S. BERNADO DO CAMPO','S. BERNARDO CAMPO','S.B DO CAMPO','S.B. DO CAMPO','S.BERNARDO DO CAMP',
                 'S.BERNARDO DO CAMPO','SAO BERNADO','SAO BERNADO DOS CAMP','SAO BERNARDO CAMPO','SAO BERNARDO DE CAMP',
                 'SAO BERNARDO DO CAMP','SAO BERNARDO DOS CAMPOS','SB CAMPO','SBCAMPO','SBERNARDO CAMPO')

update TBS002 set CLICID='SAO JOSE DOS CAMPOS'
 where CLICID in('ASO JOSE DOS CAMPOS','S J CAMPOS','SAO JOS DOS CAMPOS','SAO JOSE  DOS CAMPOS','SAO JODE DOS CAMPOS',
                 'SAO JOSE  DOS SANTOS','SAO JOSE CAMPOS','SAO JOSE CMAPOS','SAO JOSE DO CAMPOS','SAO JOSE DOS  CAMPOS',
                 'SAO JOSE DOS CAMOS','SAO JOSE DOS CAMPO','SAO JOSE DOS CMAPOS','SAO JOSE ODS CAMPOS',
                 'SAO JOSEE DOS CAMPOS','SAO JOSO DOS CAMPOS','SAO JSOE CAMPOS','S.J.CAMPOS','S.J.DOS CAMPOS',
                 'JSCAMPOS','SJ CAMPOS','SJC','SJCAMPO','SJCAMPOS','SJCAMPS','SJCCAMPOS','SJCMPOS','SJOCAMPOS',
                 'SJOSE DOS CAMPOS','SLCAMPOS','SO JOSE DOS CAMPOS','SOA JOSE CAMPOS','SOA JOSE DOS CAMPOS',
                 'SSAO JOSE DOS CAMPOS','SÃO JOSE DOS CAMPOS','SÄO JOSE DOS CAMPOS','JD. AQUARIUS','JARDIM CALIFORNIA',
                 'JD.INDUSTRIAS','SA OJOSE DOS CAMPOS','SAO  JOSE DOS CAMPOS','SA OJOSE DOS CAMPOS',
                 'SAP JOSE DOS CAMPOS','SÃO JOSÉ DOS CAMPOS','SäO JOSE DOS CAMPOS','VILA ADYANNA','S J DOS CAMPOS',
                 'S JOSE DOS CAMPOS','S.JOSE DOS CAMPOS','SAO JOSE DOS CA')

update TBS002 set CLICID='SAO PAULO'
 where CLICID in('S+O PAULO','S.PAULO','SP','SP PAULO','SPAULO','SÃO PAULO','SÃO PAULO - SP','SÄO PAULO','SAO  PAULO',
                 'SAO PAILO','SAO PAUJLO','SAO SAULO','SAO PAULOI','+AO PAULO',',AO PAULO',',SAO PAULO','.SAO PAULO',
                 '.SP','S PAULO','S'+''''+'P','SA PAULO','SA0 PAULO','SAA PAULO','SAAO PAULO','SAIO PAULO',
                 'SAO  PAULO','SAO '+''''+'PAULO','SAO -PAULO','SAO APAULO','SAO APULO','SAO LAULO','SAO PALO',
                 'SAO PAUL0','SAO PAULCO','SAO PAULIO','SAO PAULO     N§40','SAO PAULO , SP','SAO PAULO AMD BOX 4',
                 'SAO PAULO PAV.APE-BOX11','SAO PAULO S.P','SAO PAULO SERRA','SAO PAULO SP','SAO PAULO ST AMARO',
                 'SAO PAULO USP','SAO PAULO jd.MONTE ALEGRE','SAO PAULO'+'''','SAO PAULO,','SAO PAULO,,,',
                 'SAO PAULO,SP','SAO PAULO-CENTRO','SAO PAULO-SP','SAO PAULO.','SAO PAULO0','SAO PAULO3',
                 'SAO PAULOE SAPUCAI','SAO PAULOILIA','SAO PAULOP','SAO PAULOSP','SAO PAULO[','SAO PAUO','SAO PAU€P',
                 'SAO POULO','SAO PUALO','SAO PULO','SAO PµULO','SAO SAO PAULO','SAO ÁULO','SAO, PAULO','SAO,PAULO',
                 'SAO-PAULO','SAO9 PAULO','SAOM PAULO','SAOP PAULO','SAOPAULO','SAP','SAP PAULO','SAP'+'''',
                 'SASO PAULO','SASO PAULO,','SDAO PAULO','SO PAULO','SOA PAULO','SP','SP PAULO','SP SAO PAULO',
                 'SP,','SP.  SHOPPING MORUMBI','SP3','SPAULO','SQO PAULO','SÃO PAULO','SÃO PAULO,','SÄO PAULO',
                 'SÇO PAULO','SÇO PAULO SP','SAO AULO','SAO PAULO PAV.APE-BOX112','SAO PAULOA','SAO PAULO]',
                 'SAO PAULP[','SAOPULO','S¶O PAULO','SÆo Paulo','sao paulo','SAO PAULO - SP','SAOPAULO - SP')

update TBS002 set CLICID='TABOAO DA SERRA'
 where CLICID in('T DA SERRA','T SERRA','T. DA SERRA','TAB DA SERRA','TABAO DA SERRA','TABOA DA SERRA','TABOAO',
                 'TABOAO DA SERRA  SP','TABOAO DA SERRA SP','TABOAO DA SESRA','TABOAO DE SERRA','TABOAO SA SERRA',
                 'TABOAO SERRA','TABOAÖ DA SERRA','TABOÃO DA SERRA','TABOÃO DA SERRA SP','TABOÇO DA SERRA')

update TBS002 set CLICID='VARGEM GRANDE PAULISTA'
 where CLICID in('V GDE PAULISTA','VARG GDE PAULISTA','VARG GDE PTA','VARGEM G PAULISTA','VARGEM G.PAULISTA',
                 'VARGEM GD PAULISTA','VARGEM GDE PAULIST','VARGEM GDE PAULISTA','VARGEM GDE PTA.',
                 'VARGEM GDE. PAULISTA','VARGEM GR PAULISTA','VARGEM GR.PAULISTA','VARGEM GRANDE  PAULISTA',            
                 'VARGEM GRANDE PAUL','VARGEM GRANDE PAULIS','VARGEM GRANDE PAULISTA SP','VG.GRANDE PAULISTA',                 
                 'VGEM.GRDE.PAULISTA')

update TBS002 set CLICID='SAO LUIZ DO PARAITINGA'
 where CLICID in('S L PARAITINGA','S. L. PARAITINGA','S. LUIS DO PARAITINGA','S. LUIZ DO PARAITINGA',
                 'S. LUIZ PARAITINGA','S.L. DO PARAITING','SAO LUIS PARAITINGA','SAO LUIZ DE PARAITINGA',
                 'SAO LUIZ DO PARAITINGA','SAO LUIZ PARAITINGA','SÃO LUIS DO PARAITINGA','SÃO LUIZ DO PARAITINGA',
                 'SÄO LUIZ PARAITINGA')