select CLICOD,CLIPEDLIB,CLIPEDBLQ from TBS002 (noLock) where CLIPEDLIB<0 or CLIPEDBLQ<0

update TBS002 set CLIPEDLIB=0,CLIPEDBLQ=0 where CLICOD=9

select CLICOD,CLIPEDLIB,CLIPEDBLQ from TBS002 (noLock) where CLIPEDLIB>0 or CLIPEDBLQ>0

update TBS002 set CLIPEDLIB=0 where CLIPEDLIB<0
update TBS002 set CLIPEDBLQ=0 where CLIPEDBLQ<0

UPDATE TBS002 SET CLITITABT = ISNULL((SELECT SUM(CREVAL - CREVALABT - CREVALRES - CREVALREC + CREVALACR) FROM TBS056
WHERE CREDATBAI = '17530101' AND TBS056.CLICOD = TBS002.CLICOD GROUP BY TBS056.CLICOD), 0)



select * from TBS053 (nolock) where BCPTIPTRN = 'P'


