-- orcamentos
select ORCPRECUS,ORCQTDEMB,TDPCUSBAS,ORCQTDEMB*TDPCUSBAS,* from TBS0431 join TBS031 on PROCOD=TDPPROCOD
 where ORCPRECUS=0

update TBS0431 set ORCPRECUS=ORCQTDEMB*TDPCUSBAS
  from TBS0431 join TBS031 on PROCOD=TDPPROCOD where ORCPRECUS=0

-- pedidos de vendas
select PDVPRECUS,PDVQTDEMB,TDPCUSBAS,PDVQTDEMB*TDPCUSBAS,* from TBS0551 join TBS031 on PROCOD=TDPPROCOD
 where PDVPRECUS=0

update TBS0551 set PDVPRECUS=PDVQTDEMB*TDPCUSBAS
  from TBS0551 join TBS031 on PROCOD=TDPPROCOD where PDVPRECUS=0

-- notas fiscais
select NFSPRECUS,NFSQTDEMB,TDPCUSBAS,NFSQTDEMB*TDPCUSBAS,* from TBS0671 join TBS031 on PROCOD=TDPPROCOD
 where NFSPRECUS=0

update TBS0671 set NFSPRECUS=NFSQTDEMB*TDPCUSBAS
  from TBS0671 join TBS031 on PROCOD=TDPPROCOD where NFSPRECUS=0