select * 
  from TBS025  with (nolock)
 where PARVAL Like('%192.168.%')

select *
  from TBS024 with (nolock)
 where TBSSEQ='S'

declare @comando varchar(500)

--set @comando = ''

select 'update TBS024 set TBSVALSEQ=(select count(*) from ' + rtrim(TBSNOM) + ' with (nolock)) where TBSNOM=''' + rtrim(TBSNOM) +''''
  from TBS024 with (nolock)
 where TBSSEQ='S'

update TBS024 set TBSVALSEQ=(select count(*) from TBS043 with (nolock)) where TBSNOM='TBS043'

update TBS024 set TBSVALSEQ=(select count(*) from MSL001 with (nolock)) where TBSNOM='MSL001'
update TBS024 set TBSVALSEQ=(select count(*) from MSL002 with (nolock)) where TBSNOM='MSL002'
update TBS024 set TBSVALSEQ=(select count(*) from MSL009 with (nolock)) where TBSNOM='MSL009'
update TBS024 set TBSVALSEQ=(select count(*) from TBS002 with (nolock)) where TBSNOM='TBS002'
update TBS024 set TBSVALSEQ=(select count(*) from TBS004 with (nolock)) where TBSNOM='TBS004'
update TBS024 set TBSVALSEQ=(select count(*) from TBS005 with (nolock)) where TBSNOM='TBS005'
update TBS024 set TBSVALSEQ=(select count(*) from TBS006 with (nolock)) where TBSNOM='TBS006'
update TBS024 set TBSVALSEQ=(select count(*) from TBS007 with (nolock)) where TBSNOM='TBS007'
update TBS024 set TBSVALSEQ=(select count(*) from TBS008 with (nolock)) where TBSNOM='TBS008'
update TBS024 set TBSVALSEQ=(select count(*) from TBS009 with (nolock)) where TBSNOM='TBS009'
update TBS024 set TBSVALSEQ=(select count(*) from TBS010 with (nolock)) where TBSNOM='TBS010'
update TBS024 set TBSVALSEQ=(select count(*) from TBS012 with (nolock)) where TBSNOM='TBS012'
update TBS024 set TBSVALSEQ=(select count(*) from TBS017 with (nolock)) where TBSNOM='TBS017'
update TBS024 set TBSVALSEQ=(select count(*) from TBS023 with (nolock)) where TBSNOM='TBS023'
update TBS024 set TBSVALSEQ=(select count(*) from TBS026 with (nolock)) where TBSNOM='TBS026'
update TBS024 set TBSVALSEQ=(select count(*) from TBS028 with (nolock)) where TBSNOM='TBS028'
update TBS024 set TBSVALSEQ=(select count(*) from TBS033 with (nolock)) where TBSNOM='TBS033'
update TBS024 set TBSVALSEQ=(select count(*) from TBS034 with (nolock)) where TBSNOM='TBS034'
update TBS024 set TBSVALSEQ=(select count(*) from TBS035 with (nolock)) where TBSNOM='TBS035'
update TBS024 set TBSVALSEQ=(select count(*) from TBS036 with (nolock)) where TBSNOM='TBS036'
update TBS024 set TBSVALSEQ=(select count(*) from TBS037 with (nolock)) where TBSNOM='TBS037'
update TBS024 set TBSVALSEQ=(select count(*) from TBS038 with (nolock)) where TBSNOM='TBS038'
update TBS024 set TBSVALSEQ=(select count(*) from TBS042 with (nolock)) where TBSNOM='TBS042'
update TBS024 set TBSVALSEQ=(select count(*) from TBS043 with (nolock)) where TBSNOM='TBS043'
update TBS024 set TBSVALSEQ=(select count(*) from TBS044 with (nolock)) where TBSNOM='TBS044'
update TBS024 set TBSVALSEQ=(select count(*) from TBS045 with (nolock)) where TBSNOM='TBS045'
update TBS024 set TBSVALSEQ=(select count(*) from TBS046 with (nolock)) where TBSNOM='TBS046'
update TBS024 set TBSVALSEQ=(select count(*) from TBS047 with (nolock)) where TBSNOM='TBS047'
update TBS024 set TBSVALSEQ=(select count(*) from TBS048 with (nolock)) where TBSNOM='TBS048'
update TBS024 set TBSVALSEQ=(select count(*) from TBS049 with (nolock)) where TBSNOM='TBS049'
update TBS024 set TBSVALSEQ=(select count(*) from TBS050 with (nolock)) where TBSNOM='TBS050'
update TBS024 set TBSVALSEQ=(select count(*) from TBS051 with (nolock)) where TBSNOM='TBS051'
update TBS024 set TBSVALSEQ=(select count(*) from TBS052 with (nolock)) where TBSNOM='TBS052'
update TBS024 set TBSVALSEQ=(select count(*) from TBS055 with (nolock)) where TBSNOM='TBS055'
update TBS024 set TBSVALSEQ=(select count(*) from TBS0552 with (nolock)) where TBSNOM='TBS0552'
update TBS024 set TBSVALSEQ=(select count(*) from TBS067 with (nolock)) where TBSNOM='TBS067'
update TBS024 set TBSVALSEQ=(select count(*) from TBS070 with (nolock)) where TBSNOM='TBS070'
update TBS024 set TBSVALSEQ=(select count(*) from TBS072 with (nolock)) where TBSNOM='TBS072'
update TBS024 set TBSVALSEQ=(select count(*) from TBS073 with (nolock)) where TBSNOM='TBS073'
update TBS024 set TBSVALSEQ=(select count(*) from TBS074 with (nolock)) where TBSNOM='TBS074'
update TBS024 set TBSVALSEQ=(select count(*) from TBS075 with (nolock)) where TBSNOM='TBS075'
update TBS024 set TBSVALSEQ=(select count(*) from TBS076 with (nolock)) where TBSNOM='TBS076'
update TBS024 set TBSVALSEQ=(select count(*) from TBS080 with (nolock)) where TBSNOM='TBS080'
update TBS024 set TBSVALSEQ=(select count(*) from TBS082 with (nolock)) where TBSNOM='TBS082'
update TBS024 set TBSVALSEQ=(select count(*) from TBS083 with (nolock)) where TBSNOM='TBS083'
update TBS024 set TBSVALSEQ=(select count(*) from TBS088 with (nolock)) where TBSNOM='TBS088'
update TBS024 set TBSVALSEQ=(select count(*) from TBS089 with (nolock)) where TBSNOM='TBS089'
update TBS024 set TBSVALSEQ=(select count(*) from TBS097 with (nolock)) where TBSNOM='TBS097'
update TBS024 set TBSVALSEQ=(select count(*) from TBS110 with (nolock)) where TBSNOM='TBS110'
update TBS024 set TBSVALSEQ=(select count(*) from TBS112 with (nolock)) where TBSNOM='TBS112'
update TBS024 set TBSVALSEQ=(select count(*) from TBS116 with (nolock)) where TBSNOM='TBS116'
update TBS024 set TBSVALSEQ=(select count(*) from TBS119 with (nolock)) where TBSNOM='TBS119'
update TBS024 set TBSVALSEQ=(select count(*) from TBS126 with (nolock)) where TBSNOM='TBS126'
update TBS024 set TBSVALSEQ=(select count(*) from TBS135 with (nolock)) where TBSNOM='TBS135'
update TBS024 set TBSVALSEQ=(select count(*) from TBS136 with (nolock)) where TBSNOM='TBS136'
update TBS024 set TBSVALSEQ=(select count(*) from TBS137 with (nolock)) where TBSNOM='TBS137'
update TBS024 set TBSVALSEQ=(select count(*) from TMP001 with (nolock)) where TBSNOM='TMP001'
update TBS024 set TBSVALSEQ=(select count(*) from TMP002 with (nolock)) where TBSNOM='TMP002'
update TBS024 set TBSVALSEQ=(select count(*) from TMP003 with (nolock)) where TBSNOM='TMP003'
update TBS024 set TBSVALSEQ=(select count(*) from TMP004 with (nolock)) where TBSNOM='TMP004'
update TBS024 set TBSVALSEQ=(select count(*) from TMP005 with (nolock)) where TBSNOM='TMP005'
update TBS024 set TBSVALSEQ=(select count(*) from TMP006 with (nolock)) where TBSNOM='TMP006'
update TBS024 set TBSVALSEQ=(select count(*) from TMP007 with (nolock)) where TBSNOM='TMP007'
update TBS024 set TBSVALSEQ=(select count(*) from TMP008 with (nolock)) where TBSNOM='TMP008'
update TBS024 set TBSVALSEQ=(select count(*) from TMP009 with (nolock)) where TBSNOM='TMP009'
update TBS024 set TBSVALSEQ=(select count(*) from TMP010 with (nolock)) where TBSNOM='TMP010'
update TBS024 set TBSVALSEQ=(select count(*) from TMP011 with (nolock)) where TBSNOM='TMP011'
update TBS024 set TBSVALSEQ=(select count(*) from TMP015 with (nolock)) where TBSNOM='TMP015'
update TBS024 set TBSVALSEQ=(select count(*) from TMP016 with (nolock)) where TBSNOM='TMP016'

select count(*) from TBS010 with (nolock)
select count(*) from TBS015 with (nolock)
