-- insere produtos novos
select * from TBS010 A (noLock)
 where not exists(select 'ne' from JAGUAR.SIBD.dbo.TBS010 B (noLock) where B.PROCOD=A.PROCOD)


begin tran
insert into JAGUAR.SIBD.dbo.TBS010 
   select PROEMPCOD,
          PROCOD,
          PRODES,
          PROCODBAR1,
          PROCODBAR2,
          PROCODBAR3,
          PROCODBAR4,
          PROSTATUS,
          PROPESLIQ,
          PROPESBRU,
          PROEMPUM,
          PROUM1,
          PROUM1QTD,
          PROUM2,
          PROUM2QTD,
          PROUM3,
          PROUM3QTD,
          PROUM4,
          PROUM4QTD,
          GRUCOD,
          GRUEMPCOD,
          PRODATVAL,
          FORCOD,
          FOREMPCOD,
          MARCOD,
          MAREMPCOD,
          PROICMSSAI,
          PROICMSENT,
          PROPBISAI,
          PROPBIENT,
          PROIPI,
          PRODATCAD,
          FABCOD,
          FABEMPCOD,
          PROLOCFIS,
          PROREFFOR,
          PROISS,
          PROSTBA,
          PROSTBB,
          '1/1/1753',
          '1/1/1753',
          0,
          '1/1/1753',
          0,
          '1/1/1753',
          '1/1/1753',
          0,
          '1/1/1753',
          0,
          PROGERPEN,
          PROSAIEMP,
          PROSAICOD,
          PROENTEMP,
          PROENTCOD,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          PROWEB,
          MARNOM,
          FORNOM
     from TBS010 A (noLock)
    where not exists(select 'ne' from JAGUAR.SIBD.dbo.TBS010 B (noLock) where B.PROCOD=A.PROCOD)