INSERT INTO [TBS066] ([LEIBOLNOM], [LEIBOLDES], [LEIBOLDATCAD])
VALUES 
  (N'BRADESCO/002061', N'BOLETO BRADESCO BEST BAG', '20080913')

INSERT INTO [TBS066] ([LEIBOLNOM], [LEIBOLDES], [LEIBOLDATCAD])
VALUES 
  (N'REAL/803A', N'BOLETO RAL BEST BAG', '20080913')
  
INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 2, 110, N'CREDATVENREA', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 5, 5, N'CREDATEMI', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 5, 21, N'PFXCOD', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 5, 25, N'CRETIT', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 5, 31, N'CREPAR', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 5, 65, N'N', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 5, 75, N'TODAY()', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 6, 116, N'CREVALSDO', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 10, 5, N'MENSAGEM', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 11, 5, N'MENSAGEM', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 12, 5, N'MENSAGEM', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 15, 9, N'CLINOM', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 15, 55, N'CLICOD', 1)


INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 16, 9, N'CLIEND', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 17, 9, N'CLICEP', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 17, 20, N'CLICID', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 17, 60, N'CLIUF', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'BRADESCO/002061', 17, 80, N'CLICNPJCPF', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 2, 110, N'CREDATVENREA', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 5, 5, N'CREDATEMI', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 5, 21, N'PFXCOD', 0)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 5, 25, N'CRETIT', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 5, 31, N'CREPAR', 0)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 5, 70, N'N', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 5, 80, N'TODAY()', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 6, 116, N'CREVALSDO', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 8, 5, N'COBRAR 3% DE JUROS AO MES', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 9, 5, N'NAO RECEBER APOS 10 DIAS DO VENCIMENTO', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 10, 5, N'', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 14, 9, N'CLINOM', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 14, 55, N'CLICOD', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 15, 9, N'CLIEND', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 16, 9, N'CLICEP', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 16, 20, N'CLICID', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 16, 60, N'CLIUF', 1)

INSERT INTO [TBS0661] ([LEIBOLNOM], [LEIBOLLIN], [LEIBOLCOL], [LEIBOLATR], [LEIBOLTAMATR])
VALUES 
  (N'REAL/803A', 16, 80, N'CLICNPJCPF', 1)