-- ipi

select * from TBS093 (nolock)

insert into TBS093 select '00','ENTRADA COM RECUPERACAO DE CREDITO',convert(char(8),getdate(),112)
insert into TBS093 select '01','ENTRADA TRIBUTAVEL COM ALIQUOTA ZERO',convert(char(8),getdate(),112)
insert into TBS093 select '02','ENTRADA ISENTA',convert(char(8),getdate(),112)
insert into TBS093 select '03','ENTRADA NAO-TRIBUTADA',convert(char(8),getdate(),112)
insert into TBS093 select '04','ENTRADA IMUNE',convert(char(8),getdate(),112)
insert into TBS093 select '05','ENTRADA COM SUSPENSAO',convert(char(8),getdate(),112)
insert into TBS093 select '49','OUTRAS ENTRADAS',convert(char(8),getdate(),112)
insert into TBS093 select '50','SAIDA TRIBUTADA',convert(char(8),getdate(),112)
insert into TBS093 select '51','SAIDA TRIBUTAVEL COM ALIQUOTA ZERO',convert(char(8),getdate(),112)
insert into TBS093 select '52','SAIDA ISENTA',convert(char(8),getdate(),112)
insert into TBS093 select '52','SAIDA COM SUSPENSAO',convert(char(8),getdate(),112)
insert into TBS093 select '53','SAIDA NAO-TRIBUTADA',convert(char(8),getdate(),112)
insert into TBS093 select '54','SAIDA IMUNE',convert(char(8),getdate(),112)
insert into TBS093 select '55','SAIDA COM SUSPENSAO',convert(char(8),getdate(),112)
insert into TBS093 select '99','OUTRAS SAIDAS',convert(char(8),getdate(),112)

-- PIS

select * from TBS094 (nolock)

insert into TBS094 select '01',upper('OperaCAo TributAvel com AlIquota BAsica'),convert(char(8),getdate(),112)
insert into TBS094 select '02',upper('Operacao Tributavel com Aliquota Diferenciada'),convert(char(8),getdate(),112)
insert into TBS094 select '03',upper('Operacao Tributavel com Aliquota por Unidade de Medida de Produto'),convert(char(8),getdate(),112)
insert into TBS094 select '04',upper('Operacao Tributavel Monofasica - Revenda a Aliquota Zero'),convert(char(8),getdate(),112)
insert into TBS094 select '05',upper('Operacao Tributavel por Substituicao Tributaria'),convert(char(8),getdate(),112)
insert into TBS094 select '06',upper('Operacao Tributavel a Aliquota Zero'),convert(char(8),getdate(),112)
insert into TBS094 select '07',upper('Operacao Isenta da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS094 select '08',upper('Operacao sem Incidencia da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS094 select '09',upper('Operacao com Suspensao da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS094 select '49',upper('Outras Operacoes de Saida'),convert(char(8),getdate(),112)
insert into TBS094 select '50',upper('Operacao com Direito a Credito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS094 select '51',upper('Operacao com Direito a Credito - Vinculada Exclusivamente a Receita Nao-Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS094 select '52',upper('Operacao com Direito a Credito - Vinculada Exclusivamente a Receita de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '53',upper('Operacao com Direito a Credito - Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS094 select '54',upper('Operacao com Direito a Credito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '55',upper('Operacao com Direito a Credito - Vinculada a Receitas Nao Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '56',upper('Operacao com Direito a Credito - Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '60',upper('Credito Presumido - Operacao de Aquisicao Vinculada Exclusivamente a Receita Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS094 select '61',upper('Credito Presumido - Operacao de Aquisicao Vinculada Exclusivamente a Receita Nao-Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS094 select '62',upper('Credito Presumido - Operacao de Aquisicao Vinculada Exclusivamente a Receita de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '63',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS094 select '64',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '65',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Nao-Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '66',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS094 select '67',upper('Credito Presumido - Outras Operacoes'),convert(char(8),getdate(),112)
insert into TBS094 select '70',upper('Operacao de Aquisicao sem Direito a Credito'),convert(char(8),getdate(),112)
insert into TBS094 select '71',upper('Operacao de Aquisicao com Isencao'),convert(char(8),getdate(),112)
insert into TBS094 select '72',upper('Operacao de Aquisicao com Suspensao'),convert(char(8),getdate(),112)
insert into TBS094 select '73',upper('Operacao de Aquisicao a Aliquota Zero'),convert(char(8),getdate(),112)
insert into TBS094 select '74',upper('Operacao de Aquisicao sem Incidencia da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS094 select '75',upper('Operacao de Aquisicao por Substituicao Tributaria'),convert(char(8),getdate(),112)
insert into TBS094 select '98',upper('Outras Operaoces de Entrada'),convert(char(8),getdate(),112)
insert into TBS094 select '99',upper('Outras Operacoes'),convert(char(8),getdate(),112)

-- cofins

select * from TBS095 (nolock)

insert into TBS095 select '01',upper('OperaCAo TributAvel com AlIquota BAsica'),convert(char(8),getdate(),112)
insert into TBS095 select '02',upper('Operacao Tributavel com Aliquota Diferenciada'),convert(char(8),getdate(),112)
insert into TBS095 select '03',upper('Operacao Tributavel com Aliquota por Unidade de Medida de Produto'),convert(char(8),getdate(),112)
insert into TBS095 select '04',upper('Operacao Tributavel Monofasica - Revenda a Aliquota Zero'),convert(char(8),getdate(),112)
insert into TBS095 select '05',upper('Operacao Tributavel por Substituicao Tributaria'),convert(char(8),getdate(),112)
insert into TBS095 select '06',upper('Operacao Tributavel a Aliquota Zero'),convert(char(8),getdate(),112)
insert into TBS095 select '07',upper('Operacao Isenta da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS095 select '08',upper('Operacao sem Incidencia da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS095 select '09',upper('Operacao com Suspensao da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS095 select '49',upper('Outras Operacoes de Saida'),convert(char(8),getdate(),112)
insert into TBS095 select '50',upper('Operacao com Direito a Credito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS095 select '51',upper('Operacao com Direito a Credito - Vinculada Exclusivamente a Receita Nao-Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS095 select '52',upper('Operacao com Direito a Credito - Vinculada Exclusivamente a Receita de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '53',upper('Operacao com Direito a Credito - Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS095 select '54',upper('Operacao com Direito a Credito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '55',upper('Operacao com Direito a Credito - Vinculada a Receitas Nao Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '56',upper('Operacao com Direito a Credito - Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '60',upper('Credito Presumido - Operacao de Aquisicao Vinculada Exclusivamente a Receita Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS095 select '61',upper('Credito Presumido - Operacao de Aquisicao Vinculada Exclusivamente a Receita Nao-Tributada no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS095 select '62',upper('Credito Presumido - Operacao de Aquisicao Vinculada Exclusivamente a Receita de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '63',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno'),convert(char(8),getdate(),112)
insert into TBS095 select '64',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '65',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Nao-Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '66',upper('Credito Presumido - Operacao de Aquisicao Vinculada a Receitas Tributadas e Nao-Tributadas no Mercado Interno e de Exportacao'),convert(char(8),getdate(),112)
insert into TBS095 select '67',upper('Credito Presumido - Outras Operacoes'),convert(char(8),getdate(),112)
insert into TBS095 select '70',upper('Operacao de Aquisicao sem Direito a Credito'),convert(char(8),getdate(),112)
insert into TBS095 select '71',upper('Operacao de Aquisicao com Isencao'),convert(char(8),getdate(),112)
insert into TBS095 select '72',upper('Operacao de Aquisicao com Suspensao'),convert(char(8),getdate(),112)
insert into TBS095 select '73',upper('Operacao de Aquisicao a Aliquota Zero'),convert(char(8),getdate(),112)
insert into TBS095 select '74',upper('Operacao de Aquisicao sem Incidencia da Contribuicao'),convert(char(8),getdate(),112)
insert into TBS095 select '75',upper('Operacao de Aquisicao por Substituicao Tributaria'),convert(char(8),getdate(),112)
insert into TBS095 select '98',upper('Outras Operaoces de Entrada'),convert(char(8),getdate(),112)
insert into TBS095 select '99',upper('Outras Operacoes'),convert(char(8),getdate(),112)
