select 'select ' + col.name + ' from '+ obj.name + ' where ' + col.name + ' is null'
from sysobjects obj join syscolumns col on col.id = obj.id
                    join systypes typ on typ.xtype = col.xtype
where obj.name Like('TBS%') order by obj.name
                                                                                                                                                                                                                                                                                              

select PARCOD from TBS00 where PARCOD is null
select PARDES from TBS00 where PARDES is null
select PARVAL from TBS00 where PARVAL is null
select UFESIG from TBS001 where UFESIG is null
select UFENOM from TBS001 where UFENOM is null
select UFEICM from TBS001 where UFEICM is null
select UFEDATCAD from TBS001 where UFEDATCAD is null
select CLIEMPCOD from TBS002 where CLIEMPCOD is null
select CLICOD from TBS002 where CLICOD is null
select CLINOM from TBS002 where CLINOM is null
select CLINOMFAN from TBS002 where CLINOMFAN is null
select CLIEND from TBS002 where CLIEND is null
select CLICEP from TBS002 where CLICEP is null
select CLIBAI from TBS002 where CLIBAI is null
select CLICID from TBS002 where CLICID is null
select CLICONTAT from TBS002 where CLICONTAT is null
select CLITEL from TBS002 where CLITEL is null
select CLIFAX from TBS002 where CLIFAX is null
select RAMCOD from TBS002 where RAMCOD is null
select RAMEMPCOD from TBS002 where RAMEMPCOD is null
select CLICGC from TBS002 where CLICGC is null
select CLICPF from TBS002 where CLICPF is null
select CLIIES from TBS002 where CLIIES is null
select CLIIMU from TBS002 where CLIIMU is null
select CLIDATCAD from TBS002 where CLIDATCAD is null
select CLISTATUS from TBS002 where CLISTATUS is null
select CLIEMAIL from TBS002 where CLIEMAIL is null
select CLIURL from TBS002 where CLIURL is null
select CPGCOD from TBS002 where CPGCOD is null
select CPGEMPCOD from TBS002 where CPGEMPCOD is null
select VENCOD from TBS002 where VENCOD is null
select VENEMPCOD from TBS002 where VENEMPCOD is null
select CLIBLCRED from TBS002 where CLIBLCRED is null
select CLICLA from TBS002 where CLICLA is null
select CLILIC from TBS002 where CLILIC is null
select CLILICVEN from TBS002 where CLILICVEN is null
select TRNCOD from TBS002 where TRNCOD is null
select TRNEMPCOD from TBS002 where TRNEMPCOD is null
select UFESIG from TBS002 where UFESIG is null
select CLITIPPES from TBS002 where CLITIPPES is null
select CLITIPCLI from TBS002 where CLITIPCLI is null
select CLIPRICOM from TBS002 where CLIPRICOM is null
select CLIPCPVAL from TBS002 where CLIPCPVAL is null
select CLIPCPNFS from TBS002 where CLIPCPNFS is null
select CLIMCPDAT from TBS002 where CLIMCPDAT is null
select CLIMCPVAL from TBS002 where CLIMCPVAL is null
select CLIMCPNFS from TBS002 where CLIMCPNFS is null
select CLIUCPDAT from TBS002 where CLIUCPDAT is null
select CLIUCPVAL from TBS002 where CLIUCPVAL is null
select CLIUCPNFS from TBS002 where CLIUCPNFS is null
select CLIPEDLIB from TBS002 where CLIPEDLIB is null
select CLIPEDBLQ from TBS002 where CLIPEDBLQ is null
select CLITITABT from TBS002 where CLITITABT is null
select CLIPSTCOD from TBS002 where CLIPSTCOD is null
select CLIDATFUN from TBS002 where CLIDATFUN is null
select CLIINTENT from TBS002 where CLIINTENT is null
select CLIOBS from TBS002 where CLIOBS is null
select CLIDIAE11 from TBS002 where CLIDIAE11 is null
select CLIINTDIA1 from TBS002 where CLIINTDIA1 is null
select CLIDIAE12 from TBS002 where CLIDIAE12 is null
select CLIHORE11 from TBS002 where CLIHORE11 is null
select CLIINTHOR1 from TBS002 where CLIINTHOR1 is null
select CLIHORE12 from TBS002 where CLIHORE12 is null
select CLIDIAE21 from TBS002 where CLIDIAE21 is null
select CLIINTDIA2 from TBS002 where CLIINTDIA2 is null
select CLIDIAE22 from TBS002 where CLIDIAE22 is null
select CLIHORE21 from TBS002 where CLIHORE21 is null
select CLIINTHOR2 from TBS002 where CLIINTHOR2 is null
select CLIHORE22 from TBS002 where CLIHORE22 is null
select CLIDIAE31 from TBS002 where CLIDIAE31 is null
select CLIINTDIA3 from TBS002 where CLIINTDIA3 is null
select CLIDIAE32 from TBS002 where CLIDIAE32 is null
select CLIHORE31 from TBS002 where CLIHORE31 is null
select CLIINTHOR3 from TBS002 where CLIINTHOR3 is null
select CLIHORE32 from TBS002 where CLIHORE32 is null
select CLIRECENT from TBS002 where CLIRECENT is null
select CLITELREC from TBS002 where CLITELREC is null
select CLIRAMREC from TBS002 where CLIRAMREC is null
select CLICARREC from TBS002 where CLICARREC is null
select TESCOD from TBS002 where TESCOD is null
select TESEMPCOD from TBS002 where TESEMPCOD is null
select CLIISEICMS from TBS002 where CLIISEICMS is null
select CLIBLQTRN from TBS002 where CLIBLQTRN is null
select CLITIPFRE from TBS002 where CLITIPFRE is null
select CLIMAIATR from TBS002 where CLIMAIATR is null
select CLIACUATR from TBS002 where CLIACUATR is null
select CLIQTDBAI from TBS002 where CLIQTDBAI is null
select CLIACUCOM from TBS002 where CLIACUCOM is null
select CLIACUTIT from TBS002 where CLIACUTIT is null
select CLIQTDCOM from TBS002 where CLIQTDCOM is null
select CLIQTDTIT from TBS002 where CLIQTDTIT is null
select CLIIMPBLT from TBS002 where CLIIMPBLT is null
select CLIPOREMP from TBS002 where CLIPOREMP is null
select CLIPORCOD from TBS002 where CLIPORCOD is null
select CLIENDCOB from TBS002 where CLIENDCOB is null
select CLIBAICOB from TBS002 where CLIBAICOB is null
select CLICIDCOB from TBS002 where CLICIDCOB is null
select CLICEPCOB from TBS002 where CLICEPCOB is null
select CLITELCOB from TBS002 where CLITELCOB is null
select CLIFAXCOB from TBS002 where CLIFAXCOB is null
select CLICONCOB from TBS002 where CLICONCOB is null
select CLIUFECOB from TBS002 where CLIUFECOB is null
select CLIENDENT from TBS002 where CLIENDENT is null
select CLIBAIENT from TBS002 where CLIBAIENT is null
select CLICIDENT from TBS002 where CLICIDENT is null
select CLICEPENT from TBS002 where CLICEPENT is null
select CLITELENT from TBS002 where CLITELENT is null
select CLIFAXENT from TBS002 where CLIFAXENT is null
select CLICONENT from TBS002 where CLICONENT is null
select CLIUFEENT from TBS002 where CLIUFEENT is null
select CLIULTREQ from TBS002 where CLIULTREQ is null
select ENDEMPCOD from TBS003 where ENDEMPCOD is null
select ENDTIP from TBS003 where ENDTIP is null
select ENDCOD from TBS003 where ENDCOD is null
select ENDEND from TBS003 where ENDEND is null
select ENDBAI from TBS003 where ENDBAI is null
select ENDCID from TBS003 where ENDCID is null
select ENDCEP from TBS003 where ENDCEP is null
select ENDCGC from TBS003 where ENDCGC is null
select ENDCPF from TBS003 where ENDCPF is null
select ENDIES from TBS003 where ENDIES is null
select ENDIMU from TBS003 where ENDIMU is null
select ENDCONTAT from TBS003 where ENDCONTAT is null
select ENDTEL from TBS003 where ENDTEL is null
select ENDFAX from TBS003 where ENDFAX is null
select ENDMAIL from TBS003 where ENDMAIL is null
select UFESIG from TBS003 where UFESIG is null
select ENDTIPPES from TBS003 where ENDTIPPES is null
select ENDDATCAD from TBS003 where ENDDATCAD is null
select VENEMPCOD from TBS004 where VENEMPCOD is null
select VENCOD from TBS004 where VENCOD is null
select VENNOM from TBS004 where VENNOM is null
select VENNOMRED from TBS004 where VENNOMRED is null
select VENEND from TBS004 where VENEND is null
select VENBAI from TBS004 where VENBAI is null
select VENCID from TBS004 where VENCID is null
select VENCEP from TBS004 where VENCEP is null
select VENCPF from TBS004 where VENCPF is null
select VENTEL from TBS004 where VENTEL is null
select VENFAX from TBS004 where VENFAX is null
select VENRAM from TBS004 where VENRAM is null
select VENEMAIL from TBS004 where VENEMAIL is null
select VENURL from TBS004 where VENURL is null
select VENCALCOM from TBS004 where VENCALCOM is null
select VENPERCOM from TBS004 where VENPERCOM is null
select VENLOC from TBS004 where VENLOC is null
select VENUFESIG from TBS004 where VENUFESIG is null
select VENDATCAD from TBS004 where VENDATCAD is null
select TRNEMPCOD from TBS005 where TRNEMPCOD is null
select TRNCOD from TBS005 where TRNCOD is null
select TRNNOM from TBS005 where TRNNOM is null
select TRNNOMFAN from TBS005 where TRNNOMFAN is null
select TRNEND from TBS005 where TRNEND is null
select TRNBAI from TBS005 where TRNBAI is null
select TRNCEP from TBS005 where TRNCEP is null
select TRNCID from TBS005 where TRNCID is null
select TRNCGC from TBS005 where TRNCGC is null
select TRNIES from TBS005 where TRNIES is null
select TRNTEL from TBS005 where TRNTEL is null
select TRNFAX from TBS005 where TRNFAX is null
select TRNEMAIL from TBS005 where TRNEMAIL is null
select TRNURL from TBS005 where TRNURL is null
select TRNCONTAT from TBS005 where TRNCONTAT is null
select TRNUFESIG from TBS005 where TRNUFESIG is null
select TRNDATCAD from TBS005 where TRNDATCAD is null
select FOREMPCOD from TBS006 where FOREMPCOD is null
select FORCOD from TBS006 where FORCOD is null
select FORNOM from TBS006 where FORNOM is null
select FORNOMFAN from TBS006 where FORNOMFAN is null
select FOREND from TBS006 where FOREND is null
select FORBAI from TBS006 where FORBAI is null
select FORCEP from TBS006 where FORCEP is null
select FORCID from TBS006 where FORCID is null
select UFESIG from TBS006 where UFESIG is null
select FORCGC from TBS006 where FORCGC is null
select FORCPF from TBS006 where FORCPF is null
select FORIES from TBS006 where FORIES is null
select FORIMU from TBS006 where FORIMU is null
select FORTEL from TBS006 where FORTEL is null
select FORFAX from TBS006 where FORFAX is null
select FOREMAIL from TBS006 where FOREMAIL is null
select FORURL from TBS006 where FORURL is null
select FORCONTAT from TBS006 where FORCONTAT is null
select FORDATCAD from TBS006 where FORDATCAD is null
select FORLIC from TBS006 where FORLIC is null
select FORLICVEN from TBS006 where FORLICVEN is null
select FORPRICOM from TBS006 where FORPRICOM is null
select FORPCPVAL from TBS006 where FORPCPVAL is null
select FORPCPNFE from TBS006 where FORPCPNFE is null
select FORMCPDAT from TBS006 where FORMCPDAT is null
select FORMCPVAL from TBS006 where FORMCPVAL is null
select FORMCPNFE from TBS006 where FORMCPNFE is null
select FORUCPDAT from TBS006 where FORUCPDAT is null
select FORUCPVAL from TBS006 where FORUCPVAL is null
select FORUCPNFE from TBS006 where FORUCPNFE is null
select FORPEDLIB from TBS006 where FORPEDLIB is null
select FORPEDBLQ from TBS006 where FORPEDBLQ is null
select FORTITABT from TBS006 where FORTITABT is null
select FORTIPPES from TBS006 where FORTIPPES is null
select CPGCOD from TBS006 where CPGCOD is null
select CPGEMPCOD from TBS006 where CPGEMPCOD is null
select FORIPI from TBS006 where FORIPI is null
select FORDIFICM from TBS006 where FORDIFICM is null
select FORPIS from TBS006 where FORPIS is null
select FORCOF from TBS006 where FORCOF is null
select FORFRE from TBS006 where FORFRE is null
select FORCUSADM from TBS006 where FORCUSADM is null
select FORMKPCOR1 from TBS006 where FORMKPCOR1 is null
select FORMKPCOR2 from TBS006 where FORMKPCOR2 is null
select FORMKPLOJ1 from TBS006 where FORMKPLOJ1 is null
select FORMKPLOJ2 from TBS006 where FORMKPLOJ2 is null
select FORMKPREV1 from TBS006 where FORMKPREV1 is null
select FORMKPREV2 from TBS006 where FORMKPREV2 is null
select FORMKPWE11 from TBS006 where FORMKPWE11 is null
select FORMKPWE12 from TBS006 where FORMKPWE12 is null
select FORMKPWE21 from TBS006 where FORMKPWE21 is null
select FORMKPWE22 from TBS006 where FORMKPWE22 is null
select FORREDCOR1 from TBS006 where FORREDCOR1 is null
select FORREDCOR2 from TBS006 where FORREDCOR2 is null
select FORREDCOR3 from TBS006 where FORREDCOR3 is null
select FORREDCOR4 from TBS006 where FORREDCOR4 is null
select FORREDLOJ1 from TBS006 where FORREDLOJ1 is null
select FORREDLOJ2 from TBS006 where FORREDLOJ2 is null
select FORREDLOJ3 from TBS006 where FORREDLOJ3 is null
select FORREDLOJ4 from TBS006 where FORREDLOJ4 is null
select FORREDREV1 from TBS006 where FORREDREV1 is null
select FORREDREV2 from TBS006 where FORREDREV2 is null
select FORREDREV3 from TBS006 where FORREDREV3 is null
select FORREDREV4 from TBS006 where FORREDREV4 is null
select FORREDWE11 from TBS006 where FORREDWE11 is null
select FORREDWE12 from TBS006 where FORREDWE12 is null
select FORREDWE13 from TBS006 where FORREDWE13 is null
select FORREDWE14 from TBS006 where FORREDWE14 is null
select FORREDWE21 from TBS006 where FORREDWE21 is null
select FORREDWE22 from TBS006 where FORREDWE22 is null
select FORREDWE23 from TBS006 where FORREDWE23 is null
select FORREDWE24 from TBS006 where FORREDWE24 is null
select FORCMS from TBS006 where FORCMS is null
select FORPDD1 from TBS006 where FORPDD1 is null
select FORPDD2 from TBS006 where FORPDD2 is null
select FORPDD3 from TBS006 where FORPDD3 is null
select FORPDD4 from TBS006 where FORPDD4 is null
select FORPDD5 from TBS006 where FORPDD5 is null
select FORDATFUN from TBS006 where FORDATFUN is null
select FOROBS from TBS006 where FOROBS is null
select TRNCOD from TBS006 where TRNCOD is null
select TRNEMPCOD from TBS006 where TRNEMPCOD is null
select FORTESCOD from TBS006 where FORTESCOD is null
select FORTESEMP from TBS006 where FORTESEMP is null
select FORSINHAB from TBS006 where FORSINHAB is null
select FORRECATI from TBS006 where FORRECATI is null
select FORCONRES from TBS006 where FORCONRES is null
select BANEMPCOD from TBS007 where BANEMPCOD is null
select BANCOD from TBS007 where BANCOD is null
select BANNUMAGE from TBS007 where BANNUMAGE is null
select BANNCC from TBS007 where BANNCC is null
select BANNOM from TBS007 where BANNOM is null
select BANNOMAGE from TBS007 where BANNOMAGE is null
select BANCONTRA from TBS007 where BANCONTRA is null
select BANCTR from TBS007 where BANCTR is null
select BANCTRTIP from TBS007 where BANCTRTIP is null
select BANINST1 from TBS007 where BANINST1 is null
select BANINST2 from TBS007 where BANINST2 is null
select BANARQNOM from TBS007 where BANARQNOM is null
select BANEND from TBS007 where BANEND is null
select BANBAI from TBS007 where BANBAI is null
select BANCEP from TBS007 where BANCEP is null
select BANCID from TBS007 where BANCID is null
select BANTEL from TBS007 where BANTEL is null
select BANFAX from TBS007 where BANFAX is null
select BANEMAIL from TBS007 where BANEMAIL is null
select BANURL from TBS007 where BANURL is null
select BANCONTAT from TBS007 where BANCONTAT is null
select UFESIG from TBS007 where UFESIG is null
select BANDATCAD from TBS007 where BANDATCAD is null
select BANPORDIA from TBS007 where BANPORDIA is null
select BANSEQREM from TBS007 where BANSEQREM is null
select CPGEMPCOD from TBS008 where CPGEMPCOD is null
select CPGCOD from TBS008 where CPGCOD is null
select CPGMOD from TBS008 where CPGMOD is null
select CPGCOND from TBS008 where CPGCOND is null
select CPGDES from TBS008 where CPGDES is null
select CPGTIPVEN from TBS008 where CPGTIPVEN is null
select CPGDATCAD from TBS008 where CPGDATCAD is null
select CPGPRIVEN from TBS008 where CPGPRIVEN is null
select CPGDIAVEN from TBS008 where CPGDIAVEN is null
select CPGQTDDUP from TBS008 where CPGQTDDUP is null
select CPGINTDUP from TBS008 where CPGINTDUP is null
select CPGGERDUP from TBS008 where CPGGERDUP is null
select RAMEMPCOD from TBS009 where RAMEMPCOD is null
select RAMCOD from TBS009 where RAMCOD is null
select RAMDES from TBS009 where RAMDES is null
select RAMDATCAD from TBS009 where RAMDATCAD is null
select NFNUM from TBS01 where NFNUM is null
select CLICOD from TBS01 where CLICOD is null
select CLINOM from TBS01 where CLINOM is null
select CLICNPJ from TBS01 where CLICNPJ is null
select CLIINSCR from TBS01 where CLIINSCR is null
select CLIEND from TBS01 where CLIEND is null
select CLIBAI from TBS01 where CLIBAI is null
select CLICEP from TBS01 where CLICEP is null
select CLICID from TBS01 where CLICID is null
select CLIEST from TBS01 where CLIEST is null
select CLITEL from TBS01 where CLITEL is null
select CLIATI from TBS01 where CLIATI is null
select CUPNUM from TBS01 where CUPNUM is null
select NFCANCEL from TBS01 where NFCANCEL is null
select NFDATEMI from TBS01 where NFDATEMI is null
select NFVALPRO from TBS01 where NFVALPRO is null
select NFVALTOT from TBS01 where NFVALTOT is null
select NFBASEICMS from TBS01 where NFBASEICMS is null
select NFVALICMS from TBS01 where NFVALICMS is null
select NFVALDES from TBS01 where NFVALDES is null
select NFINFCOML1 from TBS01 where NFINFCOML1 is null
select NFINFCOML2 from TBS01 where NFINFCOML2 is null
select NFINFCOML3 from TBS01 where NFINFCOML3 is null
select NFINFCOML4 from TBS01 where NFINFCOML4 is null
select NFINFCOML5 from TBS01 where NFINFCOML5 is null
select NFINFCOML6 from TBS01 where NFINFCOML6 is null
select CUPVDES from TBS01 where CUPVDES is null
select CUPVAL from TBS01 where CUPVAL is null
select CCSCOD from TBS01 where CCSCOD is null
select CCSNOM from TBS01 where CCSNOM is null
select CLIDESICMS from TBS01 where CLIDESICMS is null
select PROEMPCOD from TBS010 where PROEMPCOD is null
select PROCOD from TBS010 where PROCOD is null
select PRODES from TBS010 where PRODES is null
select PROCODBAR1 from TBS010 where PROCODBAR1 is null
select PROCODBAR2 from TBS010 where PROCODBAR2 is null
select PROCODBAR3 from TBS010 where PROCODBAR3 is null
select PROCODBAR4 from TBS010 where PROCODBAR4 is null
select PROSTATUS from TBS010 where PROSTATUS is null
select PROPESLIQ from TBS010 where PROPESLIQ is null
select PROPESBRU from TBS010 where PROPESBRU is null
select PROEMPUM from TBS010 where PROEMPUM is null
select PROUM1 from TBS010 where PROUM1 is null
select PROUM1QTD from TBS010 where PROUM1QTD is null
select PROUM2 from TBS010 where PROUM2 is null
select PROUM2QTD from TBS010 where PROUM2QTD is null
select PROUM3 from TBS010 where PROUM3 is null
select PROUM3QTD from TBS010 where PROUM3QTD is null
select PROUM4 from TBS010 where PROUM4 is null
select PROUM4QTD from TBS010 where PROUM4QTD is null
select GRUCOD from TBS010 where GRUCOD is null
select GRUEMPCOD from TBS010 where GRUEMPCOD is null
select PRODATVAL from TBS010 where PRODATVAL is null
select FORCOD from TBS010 where FORCOD is null
select FOREMPCOD from TBS010 where FOREMPCOD is null
select MARCOD from TBS010 where MARCOD is null
select MAREMPCOD from TBS010 where MAREMPCOD is null
select PROICMSSAI from TBS010 where PROICMSSAI is null
select PROICMSENT from TBS010 where PROICMSENT is null
select PROPBISAI from TBS010 where PROPBISAI is null
select PROPBIENT from TBS010 where PROPBIENT is null
select PROIPI from TBS010 where PROIPI is null
select PRODATCAD from TBS010 where PRODATCAD is null
select FABCOD from TBS010 where FABCOD is null
select FABEMPCOD from TBS010 where FABEMPCOD is null
select PROLOCFIS from TBS010 where PROLOCFIS is null
select PROREFFOR from TBS010 where PROREFFOR is null
select PROISS from TBS010 where PROISS is null
select PROSTBA from TBS010 where PROSTBA is null
select PROSTBB from TBS010 where PROSTBB is null
select PROPRIVEN from TBS010 where PROPRIVEN is null
select PROPVDVAL from TBS010 where PROPVDVAL is null
select PROPVDNFS from TBS010 where PROPVDNFS is null
select PROUVDDAT from TBS010 where PROUVDDAT is null
select PROUVDVAL from TBS010 where PROUVDVAL is null
select PROUVDNFS from TBS010 where PROUVDNFS is null
select PROMVDDAT from TBS010 where PROMVDDAT is null
select PROMVDVAL from TBS010 where PROMVDVAL is null
select PROMVDNFS from TBS010 where PROMVDNFS is null
select PROPRICOM from TBS010 where PROPRICOM is null
select PROPCPVAL from TBS010 where PROPCPVAL is null
select PROPCPNFE from TBS010 where PROPCPNFE is null
select PROUCPDAT from TBS010 where PROUCPDAT is null
select PROUCPVAL from TBS010 where PROUCPVAL is null
select PROUCPNFE from TBS010 where PROUCPNFE is null
select PROMCPDAT from TBS010 where PROMCPDAT is null
select PROMCPVAL from TBS010 where PROMCPVAL is null
select PROMCPNFE from TBS010 where PROMCPNFE is null
select PROGERPEN from TBS010 where PROGERPEN is null
select PROSAIEMP from TBS010 where PROSAIEMP is null
select PROSAICOD from TBS010 where PROSAICOD is null
select PROENTEMP from TBS010 where PROENTEMP is null
select PROENTCOD from TBS010 where PROENTCOD is null
select PROWEB from TBS010 where PROWEB is null
select MARNOM from TBS010 where MARNOM is null
select FORNOM from TBS010 where FORNOM is null
select PROSTBENTA from TBS010 where PROSTBENTA is null
select PROSTBENTB from TBS010 where PROSTBENTB is null
select UNIEMPCOD from TBS011 where UNIEMPCOD is null
select UNICOD from TBS011 where UNICOD is null
select UNIDES from TBS011 where UNIDES is null
select UNIDATCAD from TBS011 where UNIDATCAD is null
select GRUEMPCOD from TBS012 where GRUEMPCOD is null
select GRUCOD from TBS012 where GRUCOD is null
select GRUDES from TBS012 where GRUDES is null
select GRUDATCAD from TBS012 where GRUDATCAD is null
select PROEMPCOD from TBS013 where PROEMPCOD is null
select INVDATLAN from TBS013 where INVDATLAN is null
select PROCOD from TBS013 where PROCOD is null
select INVITE from TBS013 where INVITE is null
select INVPRODES from TBS013 where INVPRODES is null
select INVPROLOC from TBS013 where INVPROLOC is null
select CCSEMPCOD from TBS013 where CCSEMPCOD is null
select CCSCOD from TBS013 where CCSCOD is null
select INVUNI from TBS013 where INVUNI is null
select INVQTDEMB from TBS013 where INVQTDEMB is null
select INVQTD from TBS013 where INVQTD is null
select LESEMPCOD from TBS013 where LESEMPCOD is null
select LESCOD from TBS013 where LESCOD is null
select INVDATEFE from TBS013 where INVDATEFE is null
select PROEMPCOD from TBS0131 where PROEMPCOD is null
select INVDATLAN from TBS0131 where INVDATLAN is null
select PROCOD from TBS0131 where PROCOD is null
select INVITE from TBS0131 where INVITE is null
select INVPDVNUM from TBS0131 where INVPDVNUM is null
select INVPDVITE from TBS0131 where INVPDVITE is null
select INVPDVUNI from TBS0131 where INVPDVUNI is null
select INVPDVQTDP from TBS0131 where INVPDVQTDP is null
select INVPDVEMB from TBS0131 where INVPDVEMB is null
select INVPDVQTDA from TBS0131 where INVPDVQTDA is null
select INVPDVATE from TBS0131 where INVPDVATE is null
select MAREMPCOD from TBS014 where MAREMPCOD is null
select MARCOD from TBS014 where MARCOD is null
select MARNOM from TBS014 where MARNOM is null
select MARSEQPRO from TBS014 where MARSEQPRO is null
select MARDATCAD from TBS014 where MARDATCAD is null
select PDPEMPCOD from TBS015 where PDPEMPCOD is null
select PDPCOD from TBS015 where PDPCOD is null
select PDPPROEMP from TBS015 where PDPPROEMP is null
select PDPIPI from TBS015 where PDPIPI is null
select PDPDIFICM from TBS015 where PDPDIFICM is null
select PDPPIS from TBS015 where PDPPIS is null
select PDPCOF from TBS015 where PDPCOF is null
select PDPFRE from TBS015 where PDPFRE is null
select PDPCUSADM from TBS015 where PDPCUSADM is null
select PDPCMS from TBS015 where PDPCMS is null
select PDPMKPCOR1 from TBS015 where PDPMKPCOR1 is null
select PDPMKPCOR2 from TBS015 where PDPMKPCOR2 is null
select PDPMKPLOJ1 from TBS015 where PDPMKPLOJ1 is null
select PDPMKPLOJ2 from TBS015 where PDPMKPLOJ2 is null
select PDPMKPREV1 from TBS015 where PDPMKPREV1 is null
select PDPMKPREV2 from TBS015 where PDPMKPREV2 is null
select PDPMKPWE11 from TBS015 where PDPMKPWE11 is null
select PDPMKPWE12 from TBS015 where PDPMKPWE12 is null
select PDPMKPWE21 from TBS015 where PDPMKPWE21 is null
select PDPMKPWE22 from TBS015 where PDPMKPWE22 is null
select PDPMKPPRO1 from TBS015 where PDPMKPPRO1 is null
select PDPMKPPRO2 from TBS015 where PDPMKPPRO2 is null
select PDPVALPROI from TBS015 where PDPVALPROI is null
select PDPVALPROF from TBS015 where PDPVALPROF is null
select PDPPROCOR from TBS015 where PDPPROCOR is null
select PDPPROLOJ from TBS015 where PDPPROLOJ is null
select PDPPROWE1 from TBS015 where PDPPROWE1 is null
select PDPPROWE2 from TBS015 where PDPPROWE2 is null
select PDPPROREV from TBS015 where PDPPROREV is null
select PDPPDD1 from TBS015 where PDPPDD1 is null
select PDPPDD2 from TBS015 where PDPPDD2 is null
select PDPPDD3 from TBS015 where PDPPDD3 is null
select PDPPDD4 from TBS015 where PDPPDD4 is null
select PDPPDD5 from TBS015 where PDPPDD5 is null
select PDPPREFOR from TBS015 where PDPPREFOR is null
select PDPUNI from TBS015 where PDPUNI is null
select PDPQTDEMB from TBS015 where PDPQTDEMB is null
select PDPPREUNI from TBS015 where PDPPREUNI is null
select PDPSEGFOR from TBS015 where PDPSEGFOR is null
select PDPREDCOR1 from TBS015 where PDPREDCOR1 is null
select PDPREDCOR2 from TBS015 where PDPREDCOR2 is null
select PDPREDCOR3 from TBS015 where PDPREDCOR3 is null
select PDPREDCOR4 from TBS015 where PDPREDCOR4 is null
select PDPREDLOJ1 from TBS015 where PDPREDLOJ1 is null
select PDPREDLOJ2 from TBS015 where PDPREDLOJ2 is null
select PDPREDLOJ3 from TBS015 where PDPREDLOJ3 is null
select PDPREDLOJ4 from TBS015 where PDPREDLOJ4 is null
select PDPREDREV1 from TBS015 where PDPREDREV1 is null
select PDPREDREV2 from TBS015 where PDPREDREV2 is null
select PDPREDREV3 from TBS015 where PDPREDREV3 is null
select PDPREDREV4 from TBS015 where PDPREDREV4 is null
select PDPREDWE11 from TBS015 where PDPREDWE11 is null
select PDPREDWE12 from TBS015 where PDPREDWE12 is null
select PDPREDWE13 from TBS015 where PDPREDWE13 is null
select PDPREDWE14 from TBS015 where PDPREDWE14 is null
select PDPREDWE21 from TBS015 where PDPREDWE21 is null
select PDPREDWE22 from TBS015 where PDPREDWE22 is null
select PDPREDWE23 from TBS015 where PDPREDWE23 is null
select PDPREDWE24 from TBS015 where PDPREDWE24 is null
select PDPREDPRO1 from TBS015 where PDPREDPRO1 is null
select PDPREDPRO2 from TBS015 where PDPREDPRO2 is null
select PDPREDPRO3 from TBS015 where PDPREDPRO3 is null
select PDPREDPRO4 from TBS015 where PDPREDPRO4 is null
select PDPDATALT from TBS015 where PDPDATALT is null
select PDPDATATU from TBS015 where PDPDATATU is null
select PDPSEL from TBS015 where PDPSEL is null
select PDPDATCAD from TBS015 where PDPDATCAD is null
select MOEEMPCOD from TBS015 where MOEEMPCOD is null
select MOECOD from TBS015 where MOECOD is null
select PRODES from TBS015 where PRODES is null
select USUCOD from TBS016 where USUCOD is null
select USUSEN from TBS016 where USUSEN is null
select USUCHA from TBS016 where USUCHA is null
select USUNOM from TBS016 where USUNOM is null
select USUDEP from TBS016 where USUDEP is null
select USUCAR from TBS016 where USUCAR is null
select USUEMAIL from TBS016 where USUEMAIL is null
select USUACESIM from TBS016 where USUACESIM is null
select USUDIAEXPSEN from TBS016 where USUDIAEXPSEN is null
select USUALTSEN from TBS016 where USUALTSEN is null
select USUALTSENPROLOG from TBS016 where USUALTSENPROLOG is null
select USUDATALTCAD from TBS016 where USUDATALTCAD is null
select USUBLOQ from TBS016 where USUBLOQ is null
select USUDATCAD from TBS016 where USUDATCAD is null
select USUVISPRE from TBS016 where USUVISPRE is null
select USUEMAILSEN from TBS016 where USUEMAILSEN is null
select USUCOD from TBS0161 where USUCOD is null
select EMPCOD from TBS0161 where EMPCOD is null
select USUCOD from TBS0162 where USUCOD is null
select MODNOM from TBS0162 where MODNOM is null
select MNUNOM from TBS0162 where MNUNOM is null
select USUCOD from TBS0163 where USUCOD is null
select USULESEMP from TBS0163 where USULESEMP is null
select LESCOD from TBS0163 where LESCOD is null
select LESEMPCOD from TBS0163 where LESEMPCOD is null
select USUCOD from TBS0164 where USUCOD is null
select USUTMVEMP from TBS0164 where USUTMVEMP is null
select TMVCOD from TBS0164 where TMVCOD is null
select TMVEMPCOD from TBS0164 where TMVEMPCOD is null
select GRUUSUCOD from TBS017 where GRUUSUCOD is null
select GRUUSUDES from TBS017 where GRUUSUDES is null
select GRUUSUDAT from TBS017 where GRUUSUDAT is null
select USUCOD from TBS017 where USUCOD is null
select GRUUSUCOD from TBS0171 where GRUUSUCOD is null
select USULISTCOD from TBS0171 where USULISTCOD is null
select PRGCOD from TBS018 where PRGCOD is null
select PRGNOM from TBS018 where PRGNOM is null
select PRGDES from TBS018 where PRGDES is null
select NIVNOM from TBS018 where NIVNOM is null
select PRGBLOQ from TBS018 where PRGBLOQ is null
select PRGDATCAD from TBS018 where PRGDATCAD is null
select PRGULTITEM from TBS018 where PRGULTITEM is null
select PRGBLOQMNU from TBS018 where PRGBLOQMNU is null
select PRGCOD from TBS0181 where PRGCOD is null
select PRGEVEITEM from TBS0181 where PRGEVEITEM is null
select PRGEVENOM from TBS0181 where PRGEVENOM is null
select MNUNOM from TBS019 where MNUNOM is null
select MNUDES from TBS019 where MNUDES is null
select MNUDATCAD from TBS019 where MNUDATCAD is null
select MNUNOM from TBS0191 where MNUNOM is null
select PRGCOD from TBS0191 where PRGCOD is null
select PRGEVE from TBS0191 where PRGEVE is null
select NFNUM from TBS01L1 where NFNUM is null
select CUPITEM from TBS01L1 where CUPITEM is null
select CUPPROCOD from TBS01L1 where CUPPROCOD is null
select CUPPRODES from TBS01L1 where CUPPRODES is null
select CUPSITTRI from TBS01L1 where CUPSITTRI is null
select CUPPROUNI from TBS01L1 where CUPPROUNI is null
select CUPPROQTD from TBS01L1 where CUPPROQTD is null
select CUPPROVUN from TBS01L1 where CUPPROVUN is null
select CUPPROVTO from TBS01L1 where CUPPROVTO is null
select CUPPROICMS from TBS01L1 where CUPPROICMS is null
select MODNOM from TBS020 where MODNOM is null
select MODDES from TBS020 where MODDES is null
select MODDATCAD from TBS020 where MODDATCAD is null
select NIVNOM from TBS021 where NIVNOM is null
select NIVDES from TBS021 where NIVDES is null
select NIVDATCAD from TBS021 where NIVDATCAD is null
select NIVPOS from TBS021 where NIVPOS is null
select CONID from TBS022 where CONID is null
select CONUSU from TBS022 where CONUSU is null
select CONCOMP from TBS022 where CONCOMP is null
select CONIP from TBS022 where CONIP is null
select CONPTA from TBS022 where CONPTA is null
select CONMOD from TBS022 where CONMOD is null
select CONPRGDES from TBS022 where CONPRGDES is null
select CONDATHOR from TBS022 where CONDATHOR is null
select EMPCOD from TBS023 where EMPCOD is null
select EMPNOM from TBS023 where EMPNOM is null
select EMPNOMFAN from TBS023 where EMPNOMFAN is null
select EMPEND from TBS023 where EMPEND is null
select EMPBAI from TBS023 where EMPBAI is null
select EMPCID from TBS023 where EMPCID is null
select EMPCEP from TBS023 where EMPCEP is null
select EMPCGC from TBS023 where EMPCGC is null
select EMPCPF from TBS023 where EMPCPF is null
select EMPIES from TBS023 where EMPIES is null
select EMPTEL from TBS023 where EMPTEL is null
select EMPFAX from TBS023 where EMPFAX is null
select EMPEMAIL from TBS023 where EMPEMAIL is null
select EMPURL from TBS023 where EMPURL is null
select EMPTIPPES from TBS023 where EMPTIPPES is null
select EMPDATCAD from TBS023 where EMPDATCAD is null
select EMPOSP from TBS023 where EMPOSP is null
select EMPUFESIG from TBS023 where EMPUFESIG is null
select EMPENDENT from TBS023 where EMPENDENT is null
select EMPBAIENT from TBS023 where EMPBAIENT is null
select EMPCIDENT from TBS023 where EMPCIDENT is null
select EMPCEPENT from TBS023 where EMPCEPENT is null
select EMPCGCENT from TBS023 where EMPCGCENT is null
select EMPCPFENT from TBS023 where EMPCPFENT is null
select EMPIESENT from TBS023 where EMPIESENT is null
select EMPTELENT from TBS023 where EMPTELENT is null
select EMPFAXENT from TBS023 where EMPFAXENT is null
select EMPEMAILENT from TBS023 where EMPEMAILENT is null
select EMPURLENT from TBS023 where EMPURLENT is null
select EMPENDCOB from TBS023 where EMPENDCOB is null
select EMPBAICOB from TBS023 where EMPBAICOB is null
select EMPCIDCOB from TBS023 where EMPCIDCOB is null
select EMPCEPCOB from TBS023 where EMPCEPCOB is null
select EMPCGCCOB from TBS023 where EMPCGCCOB is null
select EMPCPFCOB from TBS023 where EMPCPFCOB is null
select EMPIESCOB from TBS023 where EMPIESCOB is null
select EMPTELCOB from TBS023 where EMPTELCOB is null
select EMPFAXCOB from TBS023 where EMPFAXCOB is null
select EMPEMAILCOB from TBS023 where EMPEMAILCOB is null
select EMPURLCOB from TBS023 where EMPURLCOB is null
select EMPUFEENT from TBS023 where EMPUFEENT is null
select EMPUFECOB from TBS023 where EMPUFECOB is null
select TBSNOM from TBS024 where TBSNOM is null
select TBSDES from TBS024 where TBSDES is null
select TBSSEQ from TBS024 where TBSSEQ is null
select TBSATRNOM from TBS024 where TBSATRNOM is null
select TBSATRDES from TBS024 where TBSATRDES is null
select TBSATRTAM from TBS024 where TBSATRTAM is null
select TBSVALSEQ from TBS024 where TBSVALSEQ is null
select TBSCTR from TBS024 where TBSCTR is null
select TBSTIP from TBS024 where TBSTIP is null
select TBSZERESC from TBS024 where TBSZERESC is null
select TBSMOD from TBS024 where TBSMOD is null
select TBSNOM from TBS0241 where TBSNOM is null
select EMPCOD from TBS0241 where EMPCOD is null
select TBSSEQE from TBS0241 where TBSSEQE is null
select TBSVALSEQE from TBS0241 where TBSVALSEQE is null
select TBSZERESCE from TBS0241 where TBSZERESCE is null
select PARCHV from TBS025 where PARCHV is null
select PARDES from TBS025 where PARDES is null
select PARTIP from TBS025 where PARTIP is null
select PARVAL from TBS025 where PARVAL is null
select PARDATCAD from TBS025 where PARDATCAD is null
select TPCEMPCOD from TBS026 where TPCEMPCOD is null
select TPCNUM from TBS026 where TPCNUM is null
select TPCMDLGER from TBS026 where TPCMDLGER is null
select TPCOBS from TBS026 where TPCOBS is null
select TPCDATCAD from TBS026 where TPCDATCAD is null
select TPCCLICOD from TBS026 where TPCCLICOD is null
select TPCCLIEMP from TBS026 where TPCCLIEMP is null
select TPCCLINOM from TBS026 where TPCCLINOM is null
select VENCOD from TBS026 where VENCOD is null
select VENEMPCOD from TBS026 where VENEMPCOD is null
select TPCULTITE from TBS026 where TPCULTITE is null
select VENNOM from TBS026 where VENNOM is null
select TPCEMPCOD from TBS0261 where TPCEMPCOD is null
select TPCNUM from TBS0261 where TPCNUM is null
select TPCITE from TBS0261 where TPCITE is null
select PROCOD from TBS0261 where PROCOD is null
select PROEMPCOD from TBS0261 where PROEMPCOD is null
select TPCPRODES from TBS0261 where TPCPRODES is null
select TPCUNI from TBS0261 where TPCUNI is null
select TPCQTDEMB from TBS0261 where TPCQTDEMB is null
select TPCQTD from TBS0261 where TPCQTD is null
select TPCPRECUS from TBS0261 where TPCPRECUS is null
select TPCMDLPRO from TBS0261 where TPCMDLPRO is null
select TPCMDLITE from TBS0261 where TPCMDLITE is null
select TPCPRE from TBS0261 where TPCPRE is null
select TPCPDDITE from TBS0261 where TPCPDDITE is null
select TPCPROCLI from TBS0261 where TPCPROCLI is null
select TPCPRECON from TBS0261 where TPCPRECON is null
select TPCMDLCON from TBS0261 where TPCMDLCON is null
select TPTEMPCOD from TBS027 where TPTEMPCOD is null
select TPTCOD from TBS027 where TPTCOD is null
select TPTNOM from TBS027 where TPTNOM is null
select TPTDATCAD from TBS027 where TPTDATCAD is null
select FABEMPCOD from TBS028 where FABEMPCOD is null
select FABCOD from TBS028 where FABCOD is null
select FABNOM from TBS028 where FABNOM is null
select FABDATCAD from TBS028 where FABDATCAD is null
select SRVIP from TBS029 where SRVIP is null
select SRVPTA from TBS029 where SRVPTA is null
select SRVNUMCON from TBS029 where SRVNUMCON is null
select SRVINI from TBS029 where SRVINI is null
select SRVBLQ from TBS029 where SRVBLQ is null
select CASEMPCOD from TBS030 where CASEMPCOD is null
select CASCOD from TBS030 where CASCOD is null
select PROCOD from TBS030 where PROCOD is null
select PROEMPCOD from TBS030 where PROEMPCOD is null
select CASDES from TBS030 where CASDES is null
select CASDATCAD from TBS030 where CASDATCAD is null
select TDPEMPCOD from TBS031 where TDPEMPCOD is null
select TDPPROCOD from TBS031 where TDPPROCOD is null
select TDPPROEMP from TBS031 where TDPPROEMP is null
select TDPDATATU from TBS031 where TDPDATATU is null
select TDPVALPROI from TBS031 where TDPVALPROI is null
select TDPVALPROF from TBS031 where TDPVALPROF is null
select TDPPREFOR from TBS031 where TDPPREFOR is null
select TDPPREUNI from TBS031 where TDPPREUNI is null
select TDPCUSBAS from TBS031 where TDPCUSBAS is null
select TDPCUSREA from TBS031 where TDPCUSREA is null
select TDPPROCOR from TBS031 where TDPPROCOR is null
select TDPPROLOJ from TBS031 where TDPPROLOJ is null
select TDPPROWE1 from TBS031 where TDPPROWE1 is null
select TDPPROWE2 from TBS031 where TDPPROWE2 is null
select TDPPROREV from TBS031 where TDPPROREV is null
select TDPPREPRO1 from TBS031 where TDPPREPRO1 is null
select TDPPREPRO2 from TBS031 where TDPPREPRO2 is null
select TDPPREPRO3 from TBS031 where TDPPREPRO3 is null
select TDPPREPRO4 from TBS031 where TDPPREPRO4 is null
select TDPMKPCOR2 from TBS031 where TDPMKPCOR2 is null
select TDPPRECOR1 from TBS031 where TDPPRECOR1 is null
select TDPPRECOR2 from TBS031 where TDPPRECOR2 is null
select TDPPRECOR3 from TBS031 where TDPPRECOR3 is null
select TDPPRECOR4 from TBS031 where TDPPRECOR4 is null
select TDPMKPLOJ2 from TBS031 where TDPMKPLOJ2 is null
select TDPPRELOJ1 from TBS031 where TDPPRELOJ1 is null
select TDPPRELOJ2 from TBS031 where TDPPRELOJ2 is null
select TDPPRELOJ3 from TBS031 where TDPPRELOJ3 is null
select TDPPRELOJ4 from TBS031 where TDPPRELOJ4 is null
select TDPMKPWE12 from TBS031 where TDPMKPWE12 is null
select TDPPREWE11 from TBS031 where TDPPREWE11 is null
select TDPPREWE12 from TBS031 where TDPPREWE12 is null
select TDPPREWE13 from TBS031 where TDPPREWE13 is null
select TDPPREWE14 from TBS031 where TDPPREWE14 is null
select TDPMKPWE22 from TBS031 where TDPMKPWE22 is null
select TDPPREWE21 from TBS031 where TDPPREWE21 is null
select TDPPREWE22 from TBS031 where TDPPREWE22 is null
select TDPPREWE23 from TBS031 where TDPPREWE23 is null
select TDPPREWE24 from TBS031 where TDPPREWE24 is null
select TDPMKPREV2 from TBS031 where TDPMKPREV2 is null
select TDPPREREV1 from TBS031 where TDPPREREV1 is null
select TDPPREREV2 from TBS031 where TDPPREREV2 is null
select TDPPREREV3 from TBS031 where TDPPREREV3 is null
select TDPPREREV4 from TBS031 where TDPPREREV4 is null
select PROEMPCOD from TBS032 where PROEMPCOD is null
select ESTLOC from TBS032 where ESTLOC is null
select PROCOD from TBS032 where PROCOD is null
select ESTQTDATU from TBS032 where ESTQTDATU is null
select ESTQTDRES from TBS032 where ESTQTDRES is null
select ESTQTDPEN from TBS032 where ESTQTDPEN is null
select ESTQTDCMP from TBS032 where ESTQTDCMP is null
select ESTDATCAD from TBS032 where ESTDATCAD is null
select ESTUSUNOM from TBS032 where ESTUSUNOM is null
select ESTROTEXE from TBS032 where ESTROTEXE is null
select ESTROTDES from TBS032 where ESTROTDES is null
select ESTSEL from TBS032 where ESTSEL is null
select PRODES from TBS032 where PRODES is null
select FORCOD from TBS032 where FORCOD is null
select MARCOD from TBS032 where MARCOD is null
select PROSTATUS from TBS032 where PROSTATUS is null
select TMVEMPCOD from TBS033 where TMVEMPCOD is null
select TMVCOD from TBS033 where TMVCOD is null
select TMVDES from TBS033 where TMVDES is null
select TMVTIP from TBS033 where TMVTIP is null
select TMVDATCAD from TBS033 where TMVDATCAD is null
select TMVMOVAUT from TBS033 where TMVMOVAUT is null
select TMVINFCLI from TBS033 where TMVINFCLI is null
select TMVINFTRA from TBS033 where TMVINFTRA is null
select LESEMPCOD from TBS034 where LESEMPCOD is null
select LESCOD from TBS034 where LESCOD is null
select LESDES from TBS034 where LESDES is null
select LESDATCAD from TBS034 where LESDATCAD is null
select LOGID from TBS035 where LOGID is null
select TBSNOM from TBS035 where TBSNOM is null
select USUCOD from TBS035 where USUCOD is null
select LOGIP from TBS035 where LOGIP is null
select MODNOM from TBS035 where MODNOM is null
select EMPCOD from TBS035 where EMPCOD is null
select PRGCOD from TBS035 where PRGCOD is null
select LOGREG from TBS035 where LOGREG is null
select LOGOPE from TBS035 where LOGOPE is null
select LOGDATHOR from TBS035 where LOGDATHOR is null
select CCSEMPCOD from TBS036 where CCSEMPCOD is null
select CCSCOD from TBS036 where CCSCOD is null
select CCSNOM from TBS036 where CCSNOM is null
select CCSDATCAD from TBS036 where CCSDATCAD is null
select CCSHBL from TBS036 where CCSHBL is null
select MVIEMPCOD from TBS037 where MVIEMPCOD is null
select MVIDOC from TBS037 where MVIDOC is null
select MVIDATLAN from TBS037 where MVIDATLAN is null
select MVIDATEFE from TBS037 where MVIDATEFE is null
select TMVCOD from TBS037 where TMVCOD is null
select TMVEMPCOD from TBS037 where TMVEMPCOD is null
select CCSCOD from TBS037 where CCSCOD is null
select CCSEMPCOD from TBS037 where CCSEMPCOD is null
select MVICCSCOD from TBS037 where MVICCSCOD is null
select MVICCSNOM from TBS037 where MVICCSNOM is null
select CLICOD from TBS037 where CLICOD is null
select CLIEMPCOD from TBS037 where CLIEMPCOD is null
select MVIEMPLES from TBS037 where MVIEMPLES is null
select MVILOCORI from TBS037 where MVILOCORI is null
select MVILOCDES from TBS037 where MVILOCDES is null
select MVIULTITE from TBS037 where MVIULTITE is null
select MVIEMPCOD from TBS0371 where MVIEMPCOD is null
select MVIDOC from TBS0371 where MVIDOC is null
select MVIITE from TBS0371 where MVIITE is null
select PROEMPCOD from TBS0371 where PROEMPCOD is null
select PROCOD from TBS0371 where PROCOD is null
select MVIPRODES from TBS0371 where MVIPRODES is null
select MVIPROUNI from TBS0371 where MVIPROUNI is null
select MVIQTDPED from TBS0371 where MVIQTDPED is null
select MVIQTDATD from TBS0371 where MVIQTDATD is null
select MVIQTDEMB from TBS0371 where MVIQTDEMB is null
select PSTEMPCOD from TBS038 where PSTEMPCOD is null
select PSTCOD from TBS038 where PSTCOD is null
select PSTNOM from TBS038 where PSTNOM is null
select PSTNOMFAN from TBS038 where PSTNOMFAN is null
select PSTEND from TBS038 where PSTEND is null
select PSTCEP from TBS038 where PSTCEP is null
select PSTBAI from TBS038 where PSTBAI is null
select PSTCID from TBS038 where PSTCID is null
select PSTCONTAT from TBS038 where PSTCONTAT is null
select PSTTEL from TBS038 where PSTTEL is null
select PSTFAX from TBS038 where PSTFAX is null
select PSTEMAIL from TBS038 where PSTEMAIL is null
select PSTURL from TBS038 where PSTURL is null
select PSTIMP from TBS038 where PSTIMP is null
select VENCOD from TBS038 where VENCOD is null
select VENEMPCOD from TBS038 where VENEMPCOD is null
select UFESIG from TBS038 where UFESIG is null
select PSTTIPPES from TBS038 where PSTTIPPES is null
select PSTDATCAD from TBS038 where PSTDATCAD is null
select CSTTAB from TBS039 where CSTTAB is null
select CSTCOD from TBS039 where CSTCOD is null
select CSTDES from TBS039 where CSTDES is null
select CSTICMS from TBS039 where CSTICMS is null
select CSTMSG from TBS039 where CSTMSG is null
select CSTDATCAD from TBS039 where CSTDATCAD is null
select GOPCOD from TBS040 where GOPCOD is null
select GOPDES from TBS040 where GOPDES is null
select GOPTIP from TBS040 where GOPTIP is null
select GOPDST from TBS040 where GOPDST is null
select GOPDATCAD from TBS040 where GOPDATCAD is null
select COPTIP from TBS041 where COPTIP is null
select COPCOD from TBS041 where COPCOD is null
select COPDES from TBS041 where COPDES is null
select COPTXT from TBS041 where COPTXT is null
select COPDDE from TBS041 where COPDDE is null
select COPCODDDE from TBS041 where COPCODDDE is null
select COPDFE from TBS041 where COPDFE is null
select COPCODDFE from TBS041 where COPCODDFE is null
select COPDOP from TBS041 where COPDOP is null
select COPCODDOP from TBS041 where COPCODDOP is null
select COPDATCAD from TBS041 where COPDATCAD is null
select TESEMPCOD from TBS042 where TESEMPCOD is null
select TESCOD from TBS042 where TESCOD is null
select TESDES from TBS042 where TESDES is null
select TESTIP from TBS042 where TESTIP is null
select TESDATCAD from TBS042 where TESDATCAD is null
select TESEST from TBS042 where TESEST is null
select TESDPL from TBS042 where TESDPL is null
select TESICMS from TBS042 where TESICMS is null
select TESIPI from TBS042 where TESIPI is null
select TESISS from TBS042 where TESISS is null
select TESCOMVEN from TBS042 where TESCOMVEN is null
select TESMSG from TBS042 where TESMSG is null
select TESTXT from TBS042 where TESTXT is null
select COPCOD from TBS042 where COPCOD is null
select COPTIP from TBS042 where COPTIP is null
select TESCNTVEN from TBS042 where TESCNTVEN is null
select TESCNTCOM from TBS042 where TESCNTCOM is null
select ORCEMPCOD from TBS043 where ORCEMPCOD is null
select ORCNUM from TBS043 where ORCNUM is null
select ORCDATCAD from TBS043 where ORCDATCAD is null
select ORCPARA from TBS043 where ORCPARA is null
select ORCCLI from TBS043 where ORCCLI is null
select ORCCLIEMP from TBS043 where ORCCLIEMP is null
select ORCNOM from TBS043 where ORCNOM is null
select VENCOD from TBS043 where VENCOD is null
select VENEMPCOD from TBS043 where VENEMPCOD is null
select ORCVENCOM from TBS043 where ORCVENCOM is null
select ORCVENPDC from TBS043 where ORCVENPDC is null
select ORCOBS from TBS043 where ORCOBS is null
select TRNCOD from TBS043 where TRNCOD is null
select TRNEMPCOD from TBS043 where TRNEMPCOD is null
select ORCPESBRU from TBS043 where ORCPESBRU is null
select ORCPESLIQ from TBS043 where ORCPESLIQ is null
select ORCVOLQTD from TBS043 where ORCVOLQTD is null
select ORCVOLESP from TBS043 where ORCVOLESP is null
select ORCVOLMAR from TBS043 where ORCVOLMAR is null
select ORCVOLNUM from TBS043 where ORCVOLNUM is null
select ORCULTITE from TBS043 where ORCULTITE is null
select CPGCOD from TBS043 where CPGCOD is null
select CPGEMPCOD from TBS043 where CPGEMPCOD is null
select ORCCPGDUP from TBS043 where ORCCPGDUP is null
select ORCREQEMP from TBS043 where ORCREQEMP is null
select ORCREQCOD from TBS043 where ORCREQCOD is null
select ORCREQNOM from TBS043 where ORCREQNOM is null
select ORCREQCDC from TBS043 where ORCREQCDC is null
select ORCPEDCLI from TBS043 where ORCPEDCLI is null
select ORCDESICMS from TBS043 where ORCDESICMS is null
select ORCTIPFRE from TBS043 where ORCTIPFRE is null
select ORCPDVNUM from TBS043 where ORCPDVNUM is null
select ORCPDVDAT from TBS043 where ORCPDVDAT is null
select ORCBLQCRE from TBS043 where ORCBLQCRE is null
select ORCVALPRO from TBS043 where ORCVALPRO is null
select ORCPRAENT from TBS043 where ORCPRAENT is null
select ORCESTDES from TBS043 where ORCESTDES is null
select ORCUSUCRE from TBS043 where ORCUSUCRE is null
select ORCTIPENT from TBS043 where ORCTIPENT is null
select ORCVALFRE from TBS043 where ORCVALFRE is null
select ORCVALSEG from TBS043 where ORCVALSEG is null
select ORCVALDES from TBS043 where ORCVALDES is null
select ORCVDDTOT from TBS043 where ORCVDDTOT is null
select ORCEMPCOD from TBS0431 where ORCEMPCOD is null
select ORCNUM from TBS0431 where ORCNUM is null
select ORCITEM from TBS0431 where ORCITEM is null
select PROCOD from TBS0431 where PROCOD is null
select PROEMPCOD from TBS0431 where PROEMPCOD is null
select ORCDES from TBS0431 where ORCDES is null
select ORCQTD from TBS0431 where ORCQTD is null
select ORCUNI from TBS0431 where ORCUNI is null
select ORCQTDEMB from TBS0431 where ORCQTDEMB is null
select ORCPDDITE from TBS0431 where ORCPDDITE is null
select ORCDATENT from TBS0431 where ORCDATENT is null
select ORCPRE from TBS0431 where ORCPRE is null
select LESCOD from TBS0431 where LESCOD is null
select LESEMPCOD from TBS0431 where LESEMPCOD is null
select TESCOD from TBS0431 where TESCOD is null
select TESEMPCOD from TBS0431 where TESEMPCOD is null
select ORCTESCOM from TBS0431 where ORCTESCOM is null
select ORCTESDPL from TBS0431 where ORCTESDPL is null
select ORCTABPRE from TBS0431 where ORCTABPRE is null
select ORCPREMIN from TBS0431 where ORCPREMIN is null
select ORCPREMAX from TBS0431 where ORCPREMAX is null
select ORCPREPRO from TBS0431 where ORCPREPRO is null
select ORCPBI from TBS0431 where ORCPBI is null
select ORCPERICMS from TBS0431 where ORCPERICMS is null
select ORCCST from TBS0431 where ORCCST is null
select ORCEFS from TBS0431 where ORCEFS is null
select ORCCFOP from TBS0431 where ORCCFOP is null
select ORCBLQPRE from TBS0431 where ORCBLQPRE is null
select ORCUSUPRE from TBS0431 where ORCUSUPRE is null
select ORCSELLIBP from TBS0431 where ORCSELLIBP is null
select ORCPRECUS from TBS0431 where ORCPRECUS is null
select ORCPERCOM from TBS0431 where ORCPERCOM is null
select MOEEMPCOD from TBS044 where MOEEMPCOD is null
select MOECOD from TBS044 where MOECOD is null
select MOENOM from TBS044 where MOENOM is null
select MOESIM from TBS044 where MOESIM is null
select MOEVAL from TBS044 where MOEVAL is null
select MOEDATATU from TBS044 where MOEDATATU is null
select MOEDATCAD from TBS044 where MOEDATCAD is null
select PDCEMPCOD from TBS045 where PDCEMPCOD is null
select PDCNUM from TBS045 where PDCNUM is null
select PDCDATCAD from TBS045 where PDCDATCAD is null
select FORCOD from TBS045 where FORCOD is null
select FOREMPCOD from TBS045 where FOREMPCOD is null
select PDCOBS from TBS045 where PDCOBS is null
select COMCOD from TBS045 where COMCOD is null
select COMEMPCOD from TBS045 where COMEMPCOD is null
select PDCCPGCOD from TBS045 where PDCCPGCOD is null
select PDCCPGEMP from TBS045 where PDCCPGEMP is null
select PDCTRNCOD from TBS045 where PDCTRNCOD is null
select PDCTRNEMP from TBS045 where PDCTRNEMP is null
select PDCULTITE from TBS045 where PDCULTITE is null
select PDCBLQ from TBS045 where PDCBLQ is null
select PDCVDDTOT from TBS045 where PDCVDDTOT is null
select PDCEMPCOD from TBS0451 where PDCEMPCOD is null
select PDCNUM from TBS0451 where PDCNUM is null
select PDCITE from TBS0451 where PDCITE is null
select PROCOD from TBS0451 where PROCOD is null
select PROEMPCOD from TBS0451 where PROEMPCOD is null
select PDCDES from TBS0451 where PDCDES is null
select PDCQTD from TBS0451 where PDCQTD is null
select PDCUNI from TBS0451 where PDCUNI is null
select PDCPRE from TBS0451 where PDCPRE is null
select PDCPDDITE from TBS0451 where PDCPDDITE is null
select LESCOD from TBS0451 where LESCOD is null
select LESEMPCOD from TBS0451 where LESEMPCOD is null
select PDCQTDEMB from TBS0451 where PDCQTDEMB is null
select PDCQTDENT from TBS0451 where PDCQTDENT is null
select PDCDATPRE from TBS0451 where PDCDATPRE is null
select PDCDATFAT from TBS0451 where PDCDATFAT is null
select PDCQTDRES from TBS0451 where PDCQTDRES is null
select PDCPDVNUM from TBS0451 where PDCPDVNUM is null
select PDCPDVITE from TBS0451 where PDCPDVITE is null
select COMEMPCOD from TBS046 where COMEMPCOD is null
select COMCOD from TBS046 where COMCOD is null
select COMNOM from TBS046 where COMNOM is null
select COMSTA from TBS046 where COMSTA is null
select COMLIMCOM from TBS046 where COMLIMCOM is null
select COMLIMVEN from TBS046 where COMLIMVEN is null
select COMDATCAD from TBS046 where COMDATCAD is null
select CLIEMPCOD from TBS047 where CLIEMPCOD is null
select CLICOD from TBS047 where CLICOD is null
select REQCOD from TBS047 where REQCOD is null
select REQNOM from TBS047 where REQNOM is null
select REQCDC from TBS047 where REQCDC is null
select REQCDCDES from TBS047 where REQCDCDES is null
select REQCAR from TBS047 where REQCAR is null
select REQDEP from TBS047 where REQDEP is null
select REQTEL from TBS047 where REQTEL is null
select REQFAX from TBS047 where REQFAX is null
select REQRAM from TBS047 where REQRAM is null
select REQANI from TBS047 where REQANI is null
select REQEMAIL from TBS047 where REQEMAIL is null
select REQDATCAD from TBS047 where REQDATCAD is null
select PCBEMPCOD from TBS048 where PCBEMPCOD is null
select PCBNUM from TBS048 where PCBNUM is null
select FORCOD from TBS048 where FORCOD is null
select FOREMPCOD from TBS048 where FOREMPCOD is null
select COMCOD from TBS048 where COMCOD is null
select COMEMPCOD from TBS048 where COMEMPCOD is null
select PCBMOT from TBS048 where PCBMOT is null
select PCBTOT from TBS048 where PCBTOT is null
select PCBDATBLO from TBS048 where PCBDATBLO is null
select PCBSEL from TBS048 where PCBSEL is null
select MDSEMPCOD from TBS049 where MDSEMPCOD is null
select MDSREG from TBS049 where MDSREG is null
select MDSTIP from TBS049 where MDSTIP is null
select MDSLAN from TBS049 where MDSLAN is null
select PROCOD from TBS049 where PROCOD is null
select PROEMPCOD from TBS049 where PROEMPCOD is null
select MDSPRODES from TBS049 where MDSPRODES is null
select MDSUNI from TBS049 where MDSUNI is null
select MDSQTDEMB from TBS049 where MDSQTDEMB is null
select MDSQTD from TBS049 where MDSQTD is null
select MDSOBS from TBS049 where MDSOBS is null
select LESCOD from TBS049 where LESCOD is null
select LESEMPCOD from TBS049 where LESEMPCOD is null
select MDSUSU from TBS049 where MDSUSU is null
select MDSEMPUSU from TBS049 where MDSEMPUSU is null
select MDSMOD from TBS049 where MDSMOD is null
select MDSQTDANT from TBS049 where MDSQTDANT is null
select OCOCOD from TBS049 where OCOCOD is null
select OCOEMPCOD from TBS049 where OCOEMPCOD is null
select OCOROT from TBS049 where OCOROT is null
select OCOEMPCOD from TBS050 where OCOEMPCOD is null
select OCOROT from TBS050 where OCOROT is null
select OCOCOD from TBS050 where OCOCOD is null
select OCODES from TBS050 where OCODES is null
select OCODATCAD from TBS050 where OCODATCAD is null
select LMEEMPCOD from TBS051 where LMEEMPCOD is null
select LMEREG from TBS051 where LMEREG is null
select LMEDOC from TBS051 where LMEDOC is null
select LMEROT from TBS051 where LMEROT is null
select LMEDESROT from TBS051 where LMEDESROT is null
select LMEACA from TBS051 where LMEACA is null
select LMEDATHOR from TBS051 where LMEDATHOR is null
select LMEUSU from TBS051 where LMEUSU is null
select LMEMOD from TBS051 where LMEMOD is null
select LMEINFALT from TBS051 where LMEINFALT is null
select PROCOD from TBS051 where PROCOD is null
select PROEMPCOD from TBS051 where PROEMPCOD is null
select LMEQTDSAL from TBS051 where LMEQTDSAL is null
select LMEQTDMOV from TBS051 where LMEQTDMOV is null
select LMEQTDATU from TBS051 where LMEQTDATU is null
select LMEQTDRES from TBS051 where LMEQTDRES is null
select LMEQTDPEN from TBS051 where LMEQTDPEN is null
select LMEQTDCMP from TBS051 where LMEQTDCMP is null
select LMEUNI from TBS051 where LMEUNI is null
select LMEQTDDIS from TBS051 where LMEQTDDIS is null
select LMELOCEST from TBS051 where LMELOCEST is null
select TDCEMPCOD from TBS052 where TDCEMPCOD is null
select TDCCLICOD from TBS052 where TDCCLICOD is null
select TDCCLIEMP from TBS052 where TDCCLIEMP is null
select TDCDATCAD from TBS052 where TDCDATCAD is null
select TDCTABVALI from TBS052 where TDCTABVALI is null
select TDCTABVALF from TBS052 where TDCTABVALF is null
select TDCULTITE from TBS052 where TDCULTITE is null
select TDCORCNUM from TBS052 where TDCORCNUM is null
select TDCDATIMP from TBS052 where TDCDATIMP is null
select TDCEMPCOD from TBS0521 where TDCEMPCOD is null
select TDCCLICOD from TBS0521 where TDCCLICOD is null
select TDCITE from TBS0521 where TDCITE is null
select PROCOD from TBS0521 where PROCOD is null
select PROEMPCOD from TBS0521 where PROEMPCOD is null
select TDCPROCLI from TBS0521 where TDCPROCLI is null
select TDCPRODES from TBS0521 where TDCPRODES is null
select TDCQTD from TBS0521 where TDCQTD is null
select TDCUNI from TBS0521 where TDCUNI is null
select TDCQTDEMB from TBS0521 where TDCQTDEMB is null
select TDCPRE from TBS0521 where TDCPRE is null
select TDCALTITE from TBS0521 where TDCALTITE is null
select TDCALTPREI from TBS0521 where TDCALTPREI is null
select TDCTIPREA from TBS0521 where TDCTIPREA is null
select TDCINDREA from TBS0521 where TDCINDREA is null
select TDCPREANT from TBS0521 where TDCPREANT is null
select TDCSEL from TBS0521 where TDCSEL is null
select BCPNUMEMP from TBS053 where BCPNUMEMP is null
select BCPTIPTRN from TBS053 where BCPTIPTRN is null
select BCPNUM from TBS053 where BCPNUM is null
select BCPBLQCRE from TBS053 where BCPBLQCRE is null
select BCPBLQPRE from TBS053 where BCPBLQPRE is null
select BCPDATBLQ from TBS053 where BCPDATBLQ is null
select BCPCLIEMP from TBS053 where BCPCLIEMP is null
select BCPCLICOD from TBS053 where BCPCLICOD is null
select BCPCLINOM from TBS053 where BCPCLINOM is null
select BCPVENEMP from TBS053 where BCPVENEMP is null
select BCPVENCOD from TBS053 where BCPVENCOD is null
select BCPVENNOM from TBS053 where BCPVENNOM is null
select BCPSEL from TBS053 where BCPSEL is null
select BCPTOT from TBS053 where BCPTOT is null
select EFSCOD from TBS054 where EFSCOD is null
select EFSUFE from TBS054 where EFSUFE is null
select EFSCLIEMP from TBS054 where EFSCLIEMP is null
select EFSCLICOD from TBS054 where EFSCLICOD is null
select EFSCLINOM from TBS054 where EFSCLINOM is null
select EFSICMSENT from TBS054 where EFSICMSENT is null
select EFSICMSSAI from TBS054 where EFSICMSSAI is null
select EFSPBIENT from TBS054 where EFSPBIENT is null
select EFSPBIREV from TBS054 where EFSPBIREV is null
select EFSPBICON from TBS054 where EFSPBICON is null
select EFSCFOPENT from TBS054 where EFSCFOPENT is null
select EFSCFOPSAI from TBS054 where EFSCFOPSAI is null
select EFSMSG from TBS054 where EFSMSG is null
select EFSDATCAD from TBS054 where EFSDATCAD is null
select PDVEMPCOD from TBS055 where PDVEMPCOD is null
select PDVNUM from TBS055 where PDVNUM is null
select PDVDATCAD from TBS055 where PDVDATCAD is null
select PDVCLICOD from TBS055 where PDVCLICOD is null
select PDVCLIEMP from TBS055 where PDVCLIEMP is null
select PDVCLINOM from TBS055 where PDVCLINOM is null
select VENCOD from TBS055 where VENCOD is null
select VENEMPCOD from TBS055 where VENEMPCOD is null
select PDVVENCOM from TBS055 where PDVVENCOM is null
select PDVVENPDC from TBS055 where PDVVENPDC is null
select PDVOBS from TBS055 where PDVOBS is null
select TRNCOD from TBS055 where TRNCOD is null
select TRNEMPCOD from TBS055 where TRNEMPCOD is null
select PDVPESBRU from TBS055 where PDVPESBRU is null
select PDVPESLIQ from TBS055 where PDVPESLIQ is null
select PDVVOLQTD from TBS055 where PDVVOLQTD is null
select PDVVOLESP from TBS055 where PDVVOLESP is null
select PDVVOLMAR from TBS055 where PDVVOLMAR is null
select PDVVOLNUM from TBS055 where PDVVOLNUM is null
select PDVULTITE from TBS055 where PDVULTITE is null
select CPGCOD from TBS055 where CPGCOD is null
select CPGEMPCOD from TBS055 where CPGEMPCOD is null
select PDVCPGDUP from TBS055 where PDVCPGDUP is null
select PDVREQEMP from TBS055 where PDVREQEMP is null
select PDVREQCOD from TBS055 where PDVREQCOD is null
select PDVREQNOM from TBS055 where PDVREQNOM is null
select PDVREQCDC from TBS055 where PDVREQCDC is null
select PDVPEDCLI from TBS055 where PDVPEDCLI is null
select PDVDESICMS from TBS055 where PDVDESICMS is null
select PDVTIPFRE from TBS055 where PDVTIPFRE is null
select PDVORCNUM from TBS055 where PDVORCNUM is null
select PDVBLQCRE from TBS055 where PDVBLQCRE is null
select PDVVALFRE from TBS055 where PDVVALFRE is null
select PDVVALSEG from TBS055 where PDVVALSEG is null
select PDVVALDES from TBS055 where PDVVALDES is null
select PDVESTDES from TBS055 where PDVESTDES is null
select PDVNFSNUM from TBS055 where PDVNFSNUM is null
select PDVUSUCRE from TBS055 where PDVUSUCRE is null
select PDVTRAPRO from TBS055 where PDVTRAPRO is null
select PDVTIPENT from TBS055 where PDVTIPENT is null
select PDVVDDTOT from TBS055 where PDVVDDTOT is null
select PDVEMPCOD from TBS0551 where PDVEMPCOD is null
select PDVNUM from TBS0551 where PDVNUM is null
select PDVITEM from TBS0551 where PDVITEM is null
select PROCOD from TBS0551 where PROCOD is null
select PROEMPCOD from TBS0551 where PROEMPCOD is null
select PDVDES from TBS0551 where PDVDES is null
select PDVQTD from TBS0551 where PDVQTD is null
select PDVUNI from TBS0551 where PDVUNI is null
select PDVQTDEMB from TBS0551 where PDVQTDEMB is null
select PDVPRE from TBS0551 where PDVPRE is null
select PDVPDDITE from TBS0551 where PDVPDDITE is null
select PDVDATENT from TBS0551 where PDVDATENT is null
select LESCOD from TBS0551 where LESCOD is null
select LESEMPCOD from TBS0551 where LESEMPCOD is null
select TESCOD from TBS0551 where TESCOD is null
select TESEMPCOD from TBS0551 where TESEMPCOD is null
select PDVMOVEST from TBS0551 where PDVMOVEST is null
select PDVTESCOM from TBS0551 where PDVTESCOM is null
select PDVTESDPL from TBS0551 where PDVTESDPL is null
select PDVTABPRE from TBS0551 where PDVTABPRE is null
select PDVPREMIN from TBS0551 where PDVPREMIN is null
select PDVPREMAX from TBS0551 where PDVPREMAX is null
select PDVPREPRO from TBS0551 where PDVPREPRO is null
select PDVPBI from TBS0551 where PDVPBI is null
select PDVPERICMS from TBS0551 where PDVPERICMS is null
select PDVCST from TBS0551 where PDVCST is null
select PDVEFS from TBS0551 where PDVEFS is null
select PDVCFOP from TBS0551 where PDVCFOP is null
select PDVBLQPRE from TBS0551 where PDVBLQPRE is null
select PDVUSUPRE from TBS0551 where PDVUSUPRE is null
select PDVGERPEN from TBS0551 where PDVGERPEN is null
select PDVQTDFAT from TBS0551 where PDVQTDFAT is null
select PDVSELLIBP from TBS0551 where PDVSELLIBP is null
select PDVPRECUS from TBS0551 where PDVPRECUS is null
select PDVPERCOM from TBS0551 where PDVPERCOM is null
select CREEMPCOD from TBS056 where CREEMPCOD is null
select PFXEMPCOD from TBS056 where PFXEMPCOD is null
select CLIEMPCOD from TBS056 where CLIEMPCOD is null
select PFXCOD from TBS056 where PFXCOD is null
select CRETIT from TBS056 where CRETIT is null
select CREPAR from TBS056 where CREPAR is null
select CLICOD from TBS056 where CLICOD is null
select TPTEMPCOD from TBS056 where TPTEMPCOD is null
select TPTCOD from TBS056 where TPTCOD is null
select POREMPCOD from TBS056 where POREMPCOD is null
select PORCOD from TBS056 where PORCOD is null
select CREDATEMI from TBS056 where CREDATEMI is null
select CREDATVEN from TBS056 where CREDATVEN is null
select CREDATVENREA from TBS056 where CREDATVENREA is null
select CREVAL from TBS056 where CREVAL is null
select CREVALRES from TBS056 where CREVALRES is null
select CREVALABT from TBS056 where CREVALABT is null
select CRETIPDED from TBS056 where CRETIPDED is null
select CREVALACR from TBS056 where CREVALACR is null
select CRETIPACR from TBS056 where CRETIPACR is null
select CREVALREC from TBS056 where CREVALREC is null
select CREDATBAI from TBS056 where CREDATBAI is null
select CREOBS from TBS056 where CREOBS is null
select CRESTATUS from TBS056 where CRESTATUS is null
select CREFATURA from TBS056 where CREFATURA is null
select CREPFXFAT from TBS056 where CREPFXFAT is null
select CRETITFAT from TBS056 where CRETITFAT is null
select CRENUMBOR from TBS056 where CRENUMBOR is null
select CREDATBOR from TBS056 where CREDATBOR is null
select CRESEL from TBS056 where CRESEL is null
select CREIMPBOLRES from TBS056 where CREIMPBOLRES is null
select CRETITORI from TBS056 where CRETITORI is null
select CLINOM from TBS056 where CLINOM is null
select CRENUMBAN from TBS056 where CRENUMBAN is null
select CPAEMPCOD from TBS057 where CPAEMPCOD is null
select PFXEMPCOD from TBS057 where PFXEMPCOD is null
select FOREMPCOD from TBS057 where FOREMPCOD is null
select PFXCOD from TBS057 where PFXCOD is null
select CPATIT from TBS057 where CPATIT is null
select CPAPAR from TBS057 where CPAPAR is null
select FORCOD from TBS057 where FORCOD is null
select TPTEMPCOD from TBS057 where TPTEMPCOD is null
select TPTCOD from TBS057 where TPTCOD is null
select POREMPCOD from TBS057 where POREMPCOD is null
select PORCOD from TBS057 where PORCOD is null
select CPADATEMI from TBS057 where CPADATEMI is null
select CPADATVEN from TBS057 where CPADATVEN is null
select CPADATVENREA from TBS057 where CPADATVENREA is null
select CPAVAL from TBS057 where CPAVAL is null
select CPAVALRES from TBS057 where CPAVALRES is null
select CPAVALABT from TBS057 where CPAVALABT is null
select CPATIPDED from TBS057 where CPATIPDED is null
select CPAVALACR from TBS057 where CPAVALACR is null
select CPAVALPAG from TBS057 where CPAVALPAG is null
select CPATIPACR from TBS057 where CPATIPACR is null
select CPADATBAI from TBS057 where CPADATBAI is null
select CPAOBS from TBS057 where CPAOBS is null
select CPASTATUS from TBS057 where CPASTATUS is null
select CPAFATURA from TBS057 where CPAFATURA is null
select CPAPFXFAT from TBS057 where CPAPFXFAT is null
select CPATITFAT from TBS057 where CPATITFAT is null
select CPANUMBOR from TBS057 where CPANUMBOR is null
select CPADATBOR from TBS057 where CPADATBOR is null
select CPASEL from TBS057 where CPASEL is null
select FORNOM from TBS057 where FORNOM is null
select PRPEMP from TBS058 where PRPEMP is null
select PRPSIT from TBS058 where PRPSIT is null
select PRPNUM from TBS058 where PRPNUM is null
select PRPITEM from TBS058 where PRPITEM is null
select PROCOD from TBS058 where PROCOD is null
select PROEMPCOD from TBS058 where PROEMPCOD is null
select PRPPRODES from TBS058 where PRPPRODES is null
select PRPQTD from TBS058 where PRPQTD is null
select PRPUNI from TBS058 where PRPUNI is null
select PRPQTDEMB from TBS058 where PRPQTDEMB is null
select PRPESTLOC from TBS058 where PRPESTLOC is null
select PRPCLICOD from TBS058 where PRPCLICOD is null
select PRPCLIEMP from TBS058 where PRPCLIEMP is null
select PRPVENCOD from TBS058 where PRPVENCOD is null
select PRPVENEMP from TBS058 where PRPVENEMP is null
select PRPDATREG from TBS058 where PRPDATREG is null
select PRPPRELIQ from TBS058 where PRPPRELIQ is null
select PRPCNF from TBS058 where PRPCNF is null
select PRPNFEEMP from TBS058 where PRPNFEEMP is null
select PRPNFETIP from TBS058 where PRPNFETIP is null
select PRPNFENUM from TBS058 where PRPNFENUM is null
select PRPNFECOD from TBS058 where PRPNFECOD is null
select PRPSELPRM from TBS058 where PRPSELPRM is null
select PRPFOREMP from TBS058 where PRPFOREMP is null
select PRPFORCOD from TBS058 where PRPFORCOD is null
select PRPMAREMP from TBS058 where PRPMAREMP is null
select PRPMARCOD from TBS058 where PRPMARCOD is null
select PRPMARNOM from TBS058 where PRPMARNOM is null
select PRPNFEQTD from TBS058 where PRPNFEQTD is null
select PRPSELCNF from TBS058 where PRPSELCNF is null
select PRPSELPEN from TBS058 where PRPSELPEN is null
select PRPUSURES from TBS058 where PRPUSURES is null
select PRPUSUPEN from TBS058 where PRPUSUPEN is null
select PRPUSUCNF from TBS058 where PRPUSUCNF is null
select PRPUSUEST from TBS058 where PRPUSUEST is null
select PRPUSUINV from TBS058 where PRPUSUINV is null
select PRPDOCREM from TBS058 where PRPDOCREM is null
select PRPDOCREA from TBS058 where PRPDOCREA is null
select PRPDOCINV from TBS058 where PRPDOCINV is null
select PRPQTDREM from TBS058 where PRPQTDREM is null
select PRPQTDREA from TBS058 where PRPQTDREA is null
select PRPQTDINV from TBS058 where PRPQTDINV is null
select PRPMOVEST from TBS058 where PRPMOVEST is null
select NFEEMPCOD from TBS059 where NFEEMPCOD is null
select NFETIP from TBS059 where NFETIP is null
select NFENUM from TBS059 where NFENUM is null
select NFECOD from TBS059 where NFECOD is null
select NFENOSFOR from TBS059 where NFENOSFOR is null
select NFEEMPFC from TBS059 where NFEEMPFC is null
select NFENOM from TBS059 where NFENOM is null
select NFEUSUEFE from TBS059 where NFEUSUEFE is null
select NFEDATEMI from TBS059 where NFEDATEMI is null
select NFEULTITE from TBS059 where NFEULTITE is null
select NFEOBS from TBS059 where NFEOBS is null
select SEREMPCOD from TBS059 where SEREMPCOD is null
select SERCOD from TBS059 where SERCOD is null
select TPTEMPCOD from TBS059 where TPTEMPCOD is null
select TPTCOD from TBS059 where TPTCOD is null
select NFEGERPDC from TBS059 where NFEGERPDC is null
select NFEDADVAL from TBS059 where NFEDADVAL is null
select NFEESTORI from TBS059 where NFEESTORI is null
select NFEVALFRE from TBS059 where NFEVALFRE is null
select NFEVALDES from TBS059 where NFEVALDES is null
select NFEVDDTOT from TBS059 where NFEVDDTOT is null
select NFETOTICMS from TBS059 where NFETOTICMS is null
select NFETOTBAS from TBS059 where NFETOTBAS is null
select NFETOTIPI from TBS059 where NFETOTIPI is null
select NFEBASSUB from TBS059 where NFEBASSUB is null
select NFEVALSUB from TBS059 where NFEVALSUB is null
select NFEVALSEG from TBS059 where NFEVALSEG is null
select NFECAN from TBS059 where NFECAN is null
select NFEDATCAN from TBS059 where NFEDATCAN is null
select NFEUSUCAN from TBS059 where NFEUSUCAN is null
select NFEEMPCOD from TBS0591 where NFEEMPCOD is null
select NFETIP from TBS0591 where NFETIP is null
select NFENUM from TBS0591 where NFENUM is null
select NFECOD from TBS0591 where NFECOD is null
select NFEITE from TBS0591 where NFEITE is null
select PROCOD from TBS0591 where PROCOD is null
select PROEMPCOD from TBS0591 where PROEMPCOD is null
select NFEDES from TBS0591 where NFEDES is null
select NFEQTD from TBS0591 where NFEQTD is null
select NFEUNI from TBS0591 where NFEUNI is null
select NFEQTDEMB from TBS0591 where NFEQTDEMB is null
select NFEPRE from TBS0591 where NFEPRE is null
select NFEPDDITE from TBS0591 where NFEPDDITE is null
select LESCOD from TBS0591 where LESCOD is null
select LESEMPCOD from TBS0591 where LESEMPCOD is null
select TESCOD from TBS0591 where TESCOD is null
select TESEMPCOD from TBS0591 where TESEMPCOD is null
select NFEMOVEST from TBS0591 where NFEMOVEST is null
select NFEPBI from TBS0591 where NFEPBI is null
select NFEPERICMS from TBS0591 where NFEPERICMS is null
select NFECFOP from TBS0591 where NFECFOP is null
select NFECST from TBS0591 where NFECST is null
select NFEEFS from TBS0591 where NFEEFS is null
select NFEPDCNUM from TBS0591 where NFEPDCNUM is null
select NFEPDCITE from TBS0591 where NFEPDCITE is null
select NFEPDVNUM from TBS0591 where NFEPDVNUM is null
select NFEPDVITE from TBS0591 where NFEPDVITE is null
select NFENFSNUM from TBS0591 where NFENFSNUM is null
select NFENFSITE from TBS0591 where NFENFSITE is null
select NFEPERIPI from TBS0591 where NFEPERIPI is null
select NFEBASICMS from TBS0591 where NFEBASICMS is null
select NFEEMPCOD from TBS0592 where NFEEMPCOD is null
select NFETIP from TBS0592 where NFETIP is null
select NFENUM from TBS0592 where NFENUM is null
select NFECOD from TBS0592 where NFECOD is null
select NFEITE from TBS0592 where NFEITE is null
select NFETIPPED from TBS0592 where NFETIPPED is null
select NFEPEDEMP from TBS0592 where NFEPEDEMP is null
select NFEPEDNUM from TBS0592 where NFEPEDNUM is null
select NFEPEDITE from TBS0592 where NFEPEDITE is null
select NFEPEDUNI from TBS0592 where NFEPEDUNI is null
select NFEPEDQTD from TBS0592 where NFEPEDQTD is null
select NFEPEDEMB from TBS0592 where NFEPEDEMB is null
select NFEATEQTD from TBS0592 where NFEATEQTD is null
select NFEATEDAT from TBS0592 where NFEATEDAT is null
select NFEEMPCOD from TBS0593 where NFEEMPCOD is null
select NFETIP from TBS0593 where NFETIP is null
select NFENUM from TBS0593 where NFENUM is null
select NFECOD from TBS0593 where NFECOD is null
select NFEDATVEN from TBS0593 where NFEDATVEN is null
select NFEVALPAR from TBS0593 where NFEVALPAR is null
select HCREMPCOD from TBS060 where HCREMPCOD is null
select HCRPFXEMPCOD from TBS060 where HCRPFXEMPCOD is null
select HCRCLIEMPCOD from TBS060 where HCRCLIEMPCOD is null
select HCRPFXCOD from TBS060 where HCRPFXCOD is null
select HCRTIT from TBS060 where HCRTIT is null
select HCRPAR from TBS060 where HCRPAR is null
select HCRCLICOD from TBS060 where HCRCLICOD is null
select HCRSEQ from TBS060 where HCRSEQ is null
select HCRDAT from TBS060 where HCRDAT is null
select HCRACAO from TBS060 where HCRACAO is null
select HCRDATACAO from TBS060 where HCRDATACAO is null
select HCRDES from TBS060 where HCRDES is null
select HCRCAMPO from TBS060 where HCRCAMPO is null
select HCRVALANT from TBS060 where HCRVALANT is null
select HCRVALATU from TBS060 where HCRVALATU is null
select HCRUSU from TBS060 where HCRUSU is null
select HCRMOD from TBS060 where HCRMOD is null
select PFXEMPCOD from TBS061 where PFXEMPCOD is null
select PFXCOD from TBS061 where PFXCOD is null
select PFXDES from TBS061 where PFXDES is null
select PFXDATCAD from TBS061 where PFXDATCAD is null
select HCPEMPCOD from TBS062 where HCPEMPCOD is null
select HCPPFXEMPCOD from TBS062 where HCPPFXEMPCOD is null
select HCPFOREMPCOD from TBS062 where HCPFOREMPCOD is null
select HCPPFXCOD from TBS062 where HCPPFXCOD is null
select HCPTIT from TBS062 where HCPTIT is null
select HCPPAR from TBS062 where HCPPAR is null
select HCPFORCOD from TBS062 where HCPFORCOD is null
select HCPSEQ from TBS062 where HCPSEQ is null
select HCPDAT from TBS062 where HCPDAT is null
select HCPACAO from TBS062 where HCPACAO is null
select HCPDATACAO from TBS062 where HCPDATACAO is null
select HCPDES from TBS062 where HCPDES is null
select HCPCAMPO from TBS062 where HCPCAMPO is null
select HCPVALANT from TBS062 where HCPVALANT is null
select HCPVALATU from TBS062 where HCPVALATU is null
select HCPUSU from TBS062 where HCPUSU is null
select HCPMOD from TBS062 where HCPMOD is null
select POREMPCOD from TBS063 where POREMPCOD is null
select PORCOD from TBS063 where PORCOD is null
select PORNOM from TBS063 where PORNOM is null
select PORDATCAD from TBS063 where PORDATCAD is null
select PORMSGNFS from TBS063 where PORMSGNFS is null
select SEREMPCOD from TBS064 where SEREMPCOD is null
select SERCOD from TBS064 where SERCOD is null
select SERDES from TBS064 where SERDES is null
select SERDATCAD from TBS064 where SERDATCAD is null
select LAYNOM from TBS065 where LAYNOM is null
select LAYTIP from TBS065 where LAYTIP is null
select LAYDATCAD from TBS065 where LAYDATCAD is null
select LAYULTLIN from TBS065 where LAYULTLIN is null
select LAYMENSEQ from TBS065 where LAYMENSEQ is null
select OCNABULTLIN from TBS065 where OCNABULTLIN is null
select LAYNOM from TBS0651 where LAYNOM is null
select LAYTIP from TBS0651 where LAYTIP is null
select LAYLIN from TBS0651 where LAYLIN is null
select LAYTIPLIN from TBS0651 where LAYTIPLIN is null
select LAYCAMPO from TBS0651 where LAYCAMPO is null
select LAYPOSINI from TBS0651 where LAYPOSINI is null
select LAYPOSFIN from TBS0651 where LAYPOSFIN is null
select LAYDEC from TBS0651 where LAYDEC is null
select LAYCON from TBS0651 where LAYCON is null
select LAYDES from TBS0651 where LAYDES is null
select LAYNOM from TBS0652 where LAYNOM is null
select LAYTIP from TBS0652 where LAYTIP is null
select OCNABLIN from TBS0652 where OCNABLIN is null
select OCNABCOD from TBS0652 where OCNABCOD is null
select OCNABDES from TBS0652 where OCNABDES is null
select OCNABPRO from TBS0652 where OCNABPRO is null
select LEIBOLNOM from TBS066 where LEIBOLNOM is null
select LEIBOLDES from TBS066 where LEIBOLDES is null
select LEIBOLDATCAD from TBS066 where LEIBOLDATCAD is null
select LEIBOLNOM from TBS0661 where LEIBOLNOM is null
select LEIBOLLIN from TBS0661 where LEIBOLLIN is null
select LEIBOLCOL from TBS0661 where LEIBOLCOL is null
select LEIBOLATR from TBS0661 where LEIBOLATR is null
select LEIBOLTAMATR from TBS0661 where LEIBOLTAMATR is null
select NFSEMPCOD from TBS067 where NFSEMPCOD is null
select NFSNUM from TBS067 where NFSNUM is null
select NFSDATEMI from TBS067 where NFSDATEMI is null
select NFSUSUGER from TBS067 where NFSUSUGER is null
select NFSDATSAI from TBS067 where NFSDATSAI is null
select NFSHORSAI from TBS067 where NFSHORSAI is null
select NFSCAN from TBS067 where NFSCAN is null
select NFSDEV from TBS067 where NFSDEV is null
select NFSDATCAN from TBS067 where NFSDATCAN is null
select NFSUSUCAN from TBS067 where NFSUSUCAN is null
select SEREMPCOD from TBS067 where SEREMPCOD is null
select SERCOD from TBS067 where SERCOD is null
select NFSCLIEMP from TBS067 where NFSCLIEMP is null
select NFSCLICOD from TBS067 where NFSCLICOD is null
select NFSCLINOM from TBS067 where NFSCLINOM is null
select NFSREQCOD from TBS067 where NFSREQCOD is null
select NFSREQNOM from TBS067 where NFSREQNOM is null
select VENEMPCOD from TBS067 where VENEMPCOD is null
select VENCOD from TBS067 where VENCOD is null
select NFSVENCOM from TBS067 where NFSVENCOM is null
select NFSVENPDC from TBS067 where NFSVENPDC is null
select UFESIG from TBS067 where UFESIG is null
select CPGEMPCOD from TBS067 where CPGEMPCOD is null
select CPGCOD from TBS067 where CPGCOD is null
select NFSCPGDUP from TBS067 where NFSCPGDUP is null
select TRNEMPCOD from TBS067 where TRNEMPCOD is null
select TRNCOD from TBS067 where TRNCOD is null
select NFSPRONUM from TBS067 where NFSPRONUM is null
select NFSTIPFRE from TBS067 where NFSTIPFRE is null
select NFSDESICMS from TBS067 where NFSDESICMS is null
select NFSREQCDC from TBS067 where NFSREQCDC is null
select NFSPEDCLI from TBS067 where NFSPEDCLI is null
select NFSANTNUM from TBS067 where NFSANTNUM is null
select NFSVALFRE from TBS067 where NFSVALFRE is null
select NFSVALSEG from TBS067 where NFSVALSEG is null
select NFSVALDES from TBS067 where NFSVALDES is null
select NFSTOTOUT from TBS067 where NFSTOTOUT is null
select NFSORIEMI from TBS067 where NFSORIEMI is null
select NFSORINUM from TBS067 where NFSORINUM is null
select NFSTIP from TBS067 where NFSTIP is null
select NFSOBS from TBS067 where NFSOBS is null
select NFSVOLNUM from TBS067 where NFSVOLNUM is null
select NFSVOLMAR from TBS067 where NFSVOLMAR is null
select NFSVOLESP from TBS067 where NFSVOLESP is null
select NFSVOLQTD from TBS067 where NFSVOLQTD is null
select NFSPESLIQ from TBS067 where NFSPESLIQ is null
select NFSPESBRU from TBS067 where NFSPESBRU is null
select NFSCODFIS from TBS067 where NFSCODFIS is null
select NFSMESAPU from TBS067 where NFSMESAPU is null
select NFSANOAPU from TBS067 where NFSANOAPU is null
select NFSVDDTOT from TBS067 where NFSVDDTOT is null
select NFSEMPCOD from TBS0671 where NFSEMPCOD is null
select NFSNUM from TBS0671 where NFSNUM is null
select NFSITE from TBS0671 where NFSITE is null
select PROEMPCOD from TBS0671 where PROEMPCOD is null
select PROCOD from TBS0671 where PROCOD is null
select NFSPRODES from TBS0671 where NFSPRODES is null
select NFSQTD from TBS0671 where NFSQTD is null
select NFSUNI from TBS0671 where NFSUNI is null
select NFSQTDEMB from TBS0671 where NFSQTDEMB is null
select NFSPRE from TBS0671 where NFSPRE is null
select NFSPDDITE from TBS0671 where NFSPDDITE is null
select LESEMPCOD from TBS0671 where LESEMPCOD is null
select LESCOD from TBS0671 where LESCOD is null
select TESEMPCOD from TBS0671 where TESEMPCOD is null
select TESCOD from TBS0671 where TESCOD is null
select NFSMOVEST from TBS0671 where NFSMOVEST is null
select NFSTESCOM from TBS0671 where NFSTESCOM is null
select NFSTESDPL from TBS0671 where NFSTESDPL is null
select NFSPBI from TBS0671 where NFSPBI is null
select NFSPERICMS from TBS0671 where NFSPERICMS is null
select NFSCST from TBS0671 where NFSCST is null
select NFSEFS from TBS0671 where NFSEFS is null
select NFSCFOP from TBS0671 where NFSCFOP is null
select NFSPRECUS from TBS0671 where NFSPRECUS is null
select NFSPERCOM from TBS0671 where NFSPERCOM is null
select NFSNFEDEV from TBS0671 where NFSNFEDEV is null
select NFSQTDDEV from TBS0671 where NFSQTDDEV is null
select NFSPREDEV from TBS0671 where NFSPREDEV is null
select NFSEMPCOD from TBS0672 where NFSEMPCOD is null
select NFSNUM from TBS0672 where NFSNUM is null
select NFSPDVEMP from TBS0672 where NFSPDVEMP is null
select NFSPDVNUM from TBS0672 where NFSPDVNUM is null
select NFSQTDITE from TBS0672 where NFSQTDITE is null
select NFSPDVVAL from TBS0672 where NFSPDVVAL is null
select TCSEMPCOD from TBS068 where TCSEMPCOD is null
select TCSPERLUC from TBS068 where TCSPERLUC is null
select TCSPERCOM from TBS068 where TCSPERCOM is null
select TCSDATCAD from TBS068 where TCSDATCAD is null
select PDFPDVEMP from TBS069 where PDFPDVEMP is null
select PDFPDVNUM from TBS069 where PDFPDVNUM is null
select PDFPDVITE from TBS069 where PDFPDVITE is null
select PDFNFSEMP from TBS069 where PDFNFSEMP is null
select PDFNFSNUM from TBS069 where PDFNFSNUM is null
select PDFNFSDAT from TBS069 where PDFNFSDAT is null
select PDFNFSCAN from TBS069 where PDFNFSCAN is null
select PDFDATCAN from TBS069 where PDFDATCAN is null
select PROEMPCOD from TBS069 where PROEMPCOD is null
select PROCOD from TBS069 where PROCOD is null
select PDFPRODES from TBS069 where PDFPRODES is null
select PDFQTD from TBS069 where PDFQTD is null
select PDFUNI from TBS069 where PDFUNI is null
select PDFQTDEMB from TBS069 where PDFQTDEMB is null
select PDFPRE from TBS069 where PDFPRE is null
select PDFNFSITE from TBS069 where PDFNFSITE is null
select PDFCLIEMP from TBS069 where PDFCLIEMP is null
select PDFCLICOD from TBS069 where PDFCLICOD is null
select PDFCNTVEN from TBS069 where PDFCNTVEN is null
select PDFVENCOD from TBS069 where PDFVENCOD is null
select CMSEMPCOD from TBS070 where CMSEMPCOD is null
select CMSDOC from TBS070 where CMSDOC is null
select CMSDATPRO from TBS070 where CMSDATPRO is null
select CMSPERINI from TBS070 where CMSPERINI is null
select CMSPERFIN from TBS070 where CMSPERFIN is null
select CMSDATPAG from TBS070 where CMSDATPAG is null
select VENEMPCOD from TBS070 where VENEMPCOD is null
select VENCOD from TBS070 where VENCOD is null
select IMPEMPCOD from TBS071 where IMPEMPCOD is null
select IMPNOM from TBS071 where IMPNOM is null
select IMPTIP from TBS071 where IMPTIP is null
select IMPDES from TBS071 where IMPDES is null
select IMPDATCAD from TBS071 where IMPDATCAD is null
