select PROCOD,PRODES from TBS010 A
 where (select count(*) from TBS010 B where convert(int,B.PROCOD)=convert(int,A.PROCOD)) > 1
 order by PROCOD

select convert(int,PROCOD),count(*) from TBS010
 where PROCOD not in('TESTE','T5','T4','T3','T2')
 group by convert(int,PROCOD)
having count(*) > 1
 order by convert(int,PROCOD)

select CLICGC,count(*) from TBS002 group by CLICGC having count(*) > 1 order by CLICGC 

SELECT * INTO #T1 FROM TBS001
select * from #T1

DROP TABLE #T1

select * from TBS057 (nolock) where CPAOBS = 'IMPORTADO XML - PERDA DADOS'

select * from TBS056 (nolock) where CREOBS = 'IMPORTADO XML - PERDA DADOS' and CLICOD in(1210,1211)

select CLICGC,count(*) from TBS002 group by CLICGC having count(*) > 1 order by CLICGC 

select CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR,count(*)
  from TBS056 (nolock)
-- where CREOBS = 'IMPORTADO XML - PERDA DADOS'
 group by CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR
having count(*) > 1 order by CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR

select CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR into #T1
  from TBS056 (nolock)
-- where CREOBS = 'IMPORTADO XML - PERDA DADOS'
 group by CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR
having count(*) > 1 order by CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR

-- checa duplicidades considerando tambem o CNPJ/CPF do cliente
select TBS056.CREEMPCOD,TBS056.PFXEMPCOD,TBS056.CLIEMPCOD,TBS056.PFXCOD,TBS056.CRETIT,TBS056.CREPAR,TBS002.CLICGC,TBS002.CLICPF,count(*)
  from TBS056 (nolock) join TBS002 (nolock) on TBS002.CLIEMPCOD=TBS056.CLIEMPCOD and TBS002.CLICOD=TBS056.CLICOD
-- where CREOBS = 'IMPORTADO XML - PERDA DADOS'
 group by TBS056.CREEMPCOD,TBS056.PFXEMPCOD,TBS056.CLIEMPCOD,TBS056.PFXCOD,TBS056.CRETIT,TBS056.CREPAR,TBS002.CLICGC,TBS002.CLICPF
having count(*) > 1 order by TBS056.CREEMPCOD,TBS056.PFXEMPCOD,TBS056.CLIEMPCOD,TBS056.PFXCOD,TBS056.CRETIT,TBS056.CREPAR

select TBS056.CREEMPCOD,TBS056.PFXEMPCOD,TBS056.CLIEMPCOD,TBS056.PFXCOD,TBS056.CRETIT,TBS056.CREPAR,TBS002.CLICGC,TBS002.CLICPF into #T1
  from TBS056 (nolock) join TBS002 (nolock) on TBS002.CLIEMPCOD=TBS056.CLIEMPCOD and TBS002.CLICOD=TBS056.CLICOD
-- where CREOBS = 'IMPORTADO XML - PERDA DADOS'
 group by TBS056.CREEMPCOD,TBS056.PFXEMPCOD,TBS056.CLIEMPCOD,TBS056.PFXCOD,TBS056.CRETIT,TBS056.CREPAR,TBS002.CLICGC,TBS002.CLICPF
having count(*) > 1 order by TBS056.CREEMPCOD,TBS056.PFXEMPCOD,TBS056.CLIEMPCOD,TBS056.PFXCOD,TBS056.CRETIT,TBS056.CREPAR


DROP TABLE #T1

select A.PFXCOD as 'prefixo',A.CRETIT as 'titulo',A.CREPAR as 'parcela',A.CLICOD as 'cod-cliente',B.CLINOM as 'nome-cliente',B.CLIDATCAD as 'data-cadastro',
       A.PORCOD as 'portador',A.CREDATEMI as 'data-emissao',isnull(A.CREDATBAI,'') as 'data-baixa',B.CLICGC as 'CNPJ',B.CLICPF as 'CPF',A.CREOBS as 'observacao'
  from #T1 T join TBS056 A (nolock) on A.CREEMPCOD=T.CREEMPCOD and A.PFXEMPCOD=T.PFXEMPCOD and A.CLIEMPCOD=T.CLIEMPCOD and A.PFXCOD=T.PFXCOD and
                                       A.CRETIT=T.CRETIT and A.CREPAR=T.CREPAR
             join TBS002 B (nolock) on B.CLIEMPCOD=A.CLIEMPCOD and B.CLICOD=A.CLICOD

select TBS056.PFXCOD as 'prefixo',TBS056.CRETIT as 'titulo',TBS056.CREPAR as 'parcela',TBS056.CLICOD as 'cod-cliente',TBS002.CLINOM as 'nome-cliente',
       TBS002.CLIDATCAD as 'data-cadastro',TBS056.PORCOD as 'portador',isnull(TBS056.CREDATBAI,'') as 'data-baixa'
  from #T1 join TBS056 (nolock) on TBS056.CREEMPCOD=#T1.CREEMPCOD and TBS056.PFXEMPCOD=#T1.PFXEMPCOD and TBS056.CLIEMPCOD=#T1.CLIEMPCOD and
                                   TBS056.PFXCOD=#T1.PFXCOD and TBS056.CRETIT=#T1.CRETIT and TBS056.CREPAR=#T1.CREPAR
           join TBS002 (nolock) on TBS002.CLIEMPCOD=TBS056.CLIEMPCOD and TBS002.CLICOD=TBS056.CLICOD

select * from TBS056
 where --CREDATBAI = '17530101' and
       exists(select '' from #T1 where TBS056.CREEMPCOD=#T1.CREEMPCOD and TBS056.PFXEMPCOD=#T1.PFXEMPCOD and TBS056.CLIEMPCOD=#T1.CLIEMPCOD and
                                   TBS056.PFXCOD=#T1.PFXCOD and TBS056.CRETIT=#T1.CRETIT and TBS056.CREPAR=#T1.CREPAR)
