select a.NFENUM,
       (select dbo.NFETOTLIQ(b.NFEEMPCOD, b.NFETIP, b.NFENUM, b.NFECOD, b.SEREMPCOD, b.SERCOD) 
          from TBS059 b (nolock)
         where b.NFEEMPCOD=a.NFEEMPCOD and b.SEREMPCOD=a.SEREMPCOD and b.SERCOD=a.SERCOD and b.NFETIP=a.NFETIP and b.NFECOD=a.NFECOD and b.NFENUM=a.NFENUM),
       (select sum(NFETOTOPEITE) from TBS0591 c (nolock)
            where c.NFEEMPCOD=a.NFEEMPCOD and c.SEREMPCOD=a.SEREMPCOD and c.SERCOD=a.SERCOD and c.NFETIP=a.NFETIP and c.NFECOD=a.NFECOD and c.NFENUM=a.NFENUM and c.NFEITE=d.NFEITE),
       sum(dbo.NFETOTBICMS(a.NFEEMPCOD, a.NFETIP, a.NFENUM ,a.NFECOD ,a.SEREMPCOD, a.SERCOD))
  from TBS059 a (nolock)
       inner join TBS0591 d (nolock) on d.NFEEMPCOD=a.NFEEMPCOD and d.SEREMPCOD=a.SEREMPCOD and d.SERCOD=a.SERCOD and d.NFETIP=a.NFETIP and d.NFECOD=a.NFECOD and d.NFENUM=a.NFENUM
 where a.NFEDATEFE between '20180301' and '20180331' and a.NFECAN='N' and a.NFETIP='N' and d.NFEBASICMS > 0
 group by a.NFEEMPCOD, a.SEREMPCOD, a.SERCOD, a.NFETIP, a.NFECOD, a.NFENUM


select TBS059.NFENUM,
       TBS0591.NFETOTOPEITE,
       TBS0591.NFEBASICMS
  from TBS059 (nolock)
       inner join TBS0591 (nolock) on TBS0591.NFEEMPCOD=TBS059.NFEEMPCOD and TBS0591.SEREMPCOD=TBS059.SEREMPCOD and TBS0591.SERCOD=TBS059.SERCOD and
                                      TBS0591.NFETIP=TBS059.NFETIP and TBS0591.NFECOD=TBS059.NFECOD and TBS0591.NFENUM=TBS059.NFENUM
 where TBS059.NFEDATEFE between '20180301' and '20180331' and TBS059.NFECAN='N' and TBS059.NFETIP='N' and TBS0591.NFEBASICMS > 0
       and round(TBS0591.NFEBASICMS,2) > round(TBS0591.NFETOTOPEITE,2)
 order by TBS0591.NFENUM, TBS0591.NFEITE

-- group by a.NFEEMPCOD, a.SEREMPCOD, a.SERCOD, a.NFETIP, a.NFECOD, a.NFENUM

