INSERT INTO [TBS025] ([PARCHV], [PARDES], [PARTIP], [PARVAL], [PARDATCAD])
VALUES 
  (1072, 'PROGRAMA PARA EMISSAO DE NOTA FISCAL DE SAIDA', 'C', 'RVEN038', '20080924')
GO

INSERT INTO [TBS025] ([PARCHV], [PARDES], [PARTIP], [PARVAL], [PARDATCAD])
VALUES 
  (1073, 'PROGRAMA PARA EMISSAO DE NOTA FISCAL DE ENTRADA', 'C', 'REST047', '20080925')
GO

INSERT INTO [TBS025] ([PARCHV], [PARDES], [PARTIP], [PARVAL], [PARDATCAD])
VALUES 
  (1074, 'RESTRINGIR A ALTERACAO DOS ITENS DO PEDIDO DE VENDAS', 'C', 'S', '20081013')
GO