select PDPCOD,
       (select PRODES from TBS010 (nolock) where PROCOD=PDPCOD),
       PDPPREUNI,
       dbo.PDPCUSBAS(0,PDPCOD),
       PDPIPI,
       PDPPORST,
       PDPDIFICM,
       PDPPIS,
       PDPCOF,
       PDPFRE,
       PDPCUSADM,
       PDPCMS,
       PDPPDD1,
       PDPPDD2,
       PDPPDD3,
       PDPPDD4,
       PDPPDD5,
       PDPMKPCOR1,
       PDPMKPCOR2,
       PDPMKPLOJ1,
       PDPMKPLOJ2,
       *
  from TBS015 (nolock) where Left(PDPCOD,4)='1850'