-- TABELA QUE REGISTRA O LOG
SELECT * FROM TBS035 NOLOCK


-- POPULA O PROLOGID
DECLARE @counter int
SET @counter = 0
update TBS010 
set @counter = PROLOGID = @counter + 1 

-- OBTEM O MAIOR ID
SELECT MAX(PROLOGID) FROM TBS010 NOLOCK

UPDATE TBS025 SET PARVAL = (SELECT Ltrim(str(MAX(PROLOGID),10)) FROM TBS010 NOLOCK)
--SELECT * FROM TBS025 NOLOCK
WHERE PARCHV = 1321

SELECT * FROM TBS025 NOLOCK
WHERE PARCHV = 1321




