select 'CREDITO',
       PFXCOD,
       --case when CRETITORI = 'A' then 'NF' else 'MANUAL' end,
       CRETIT,
       CREPAR,
       TBS056.CLICOD,
       TPTCOD,
       PORCOD,
       CREDATEMI,
       dbo.CREDATVENREA(CREEMPCOD,PFXEMPCOD,TBS056.CLIEMPCOD,PFXCOD,CRETIT,CREPAR,TBS056.CLICOD),
       dbo.CREVALSDO(CREEMPCOD,PFXEMPCOD,TBS056.CLIEMPCOD,PFXCOD,CRETIT,CREPAR,TBS056.CLICOD) as 'previsto',
       CREVALREC as 'efetivo',
       TBS002.CLINOM,
       'CLIENTE'
  from TBS056 (nolock) join TBS002 (nolock) on TBS056.CLIEMPCOD = TBS002.CLIEMPCOD and TBS056.CLICOD = TBS002.CLICOD
 where dbo.CREDATVENREA(CREEMPCOD,PFXEMPCOD,TBS056.CLIEMPCOD,PFXCOD,CRETIT,CREPAR,TBS056.CLICOD) between '20121101' and '20121130'

select top 1 CLINOM from TBS056

declare @drec datetime ,@dpag datetime ,@dini datetime ,@dfin datetime

set @drec = (select min(dbo.CREDATVENREA(CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR,CLICOD)) from TBS056 (nolock) 
              where dbo.CREDATVENREA(CREEMPCOD,PFXEMPCOD,CLIEMPCOD,PFXCOD,CRETIT,CREPAR,CLICOD) between '20121101' and '20121130')

set @dpag = (select min(dbo.CPADATVENREA(CPAEMPCOD,PFXEMPCOD,FOREMPCOD,PFXCOD,CPATIT,CPAPAR,FORCOD)) from TBS057 (nolock) 
              where dbo.CPADATVENREA(CPAEMPCOD,PFXEMPCOD,FOREMPCOD,PFXCOD,CPATIT,CPAPAR,FORCOD) between '20121101' and '20121130')

if @drec > @dpag
   set @dini = @dpag
else
   set @dini = @drec

select 

select @drec
select @dpag
select @dini

select 'DEBITO',
       PFXCOD,
       CPATIT,
       CPAPAR,
       TBS057.FORCOD,
       TPTCOD,
       PORCOD,
       CPADATEMI,
       dbo.CPADATVENREA(CPAEMPCOD,PFXEMPCOD,TBS057.FOREMPCOD,PFXCOD,CPATIT,CPAPAR,TBS057.FORCOD),
       dbo.CPAVALSDO(CPAEMPCOD,PFXEMPCOD,TBS006.FOREMPCOD,PFXCOD,CPATIT,CPAPAR,TBS006.FORCOD) as 'previsto',
       CPAVALPAG as 'efetivo',
       TBS006.FORNOM,
       'FORNECEDOR'
  from TBS057 (nolock) join TBS006 (nolock) on TBS057.FOREMPCOD = TBS006.FOREMPCOD and TBS057.FORCOD = TBS006.FORCOD
 where dbo.CPADATVENREA(CPAEMPCOD,PFXEMPCOD,TBS057.FOREMPCOD,PFXCOD,CPATIT,CPAPAR,TBS057.FORCOD) between '20121101' and '20121130'