select TBS032.PROCOD,TBS010.PRODES,PROUM1,ESTQTDATU,ESTQTDRES,ESTQTDATU-ESTQTDRES as 'DISPONIVEL',ESTQTDPEN,ESTQTDCMP,
       ESTQTDPEN-(ESTQTDATU-ESTQTDRES)-ESTQTDCMP as 'COMPRAR'
  from TBS032 (noLock) join TBS010 (noLock) on TBS032.PROCOD=TBS010.PROCOD
 where ESTLOC=1 and ESTQTDPEN > (ESTQTDATU-ESTQTDRES)+ESTQTDCMP