-- PROMOCAO
SELECT PDPCOD, PDPPREPRO2 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREPRO2 = 0, PDPREDPRO2 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM2 = '' AND PDPPREPRO2 > 0 
ORDER BY PDPPREPRO2, PDPCOD

SELECT PDPCOD, PDPPREPRO3 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREPRO3 = 0, PDPREDPRO3 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM3 = '' AND PDPPREPRO3 > 0 
ORDER BY PDPPREPRO3, PDPCOD

SELECT PDPCOD, PDPPREPRO4 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREPRO4 = 0, PDPREDPRO4 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM4 = '' AND PDPPREPRO4 > 0 
ORDER BY PDPPREPRO4, PDPCOD

-- Preco CORPORATIVO 2, 3, 4
SELECT PDPCOD, PDPPRECOR2, PDPREDCOR2 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPRECOR2 = 0, PDPREDCOR2 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM2 = '' AND PDPPRECOR2 > 0 
ORDER BY PDPPRECOR2, PDPCOD

SELECT PDPCOD, PDPPRECOR3 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPRECOR3 = 0, PDPREDCOR3 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM3 = '' AND PDPPRECOR3 > 0 
ORDER BY PDPPRECOR3, PDPCOD

SELECT PDPCOD, PDPPRECOR4 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPRECOR4 = 0, PDPREDCOR4 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM4 = '' AND PDPPRECOR4 > 0 
ORDER BY PDPPRECOR4, PDPCOD

-- Preco LOJA 2, 3, 4
SELECT PDPCOD, PDPPRELOJ2 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPRELOJ2 = 0, PDPREDLOJ2 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM2 = '' AND PDPPRELOJ2 > 0 
ORDER BY PDPPRELOJ2, PDPCOD

SELECT PDPCOD, PDPPRELOJ3 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPRELOJ3 = 0, PDPREDLOJ3 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM3 = '' AND PDPPRELOJ3 > 0
ORDER BY PDPPRELOJ3, PDPCOD

SELECT PDPCOD, PDPPRELOJ4 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPRELOJ4 = 0, , PDPREDLOJ4 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM4 = '' AND PDPPRELOJ4 > 0 
ORDER BY PDPPRELOJ4, PDPCOD

-- Preco REVENDA 2, 3, 4
SELECT PDPCOD, PDPPREREV2 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREREV2 = 0, PDPREDREV2 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM2 = '' AND PDPPREREV2 > 0 
ORDER BY PDPPREREV2, PDPCOD

SELECT PDPCOD, PDPPREREV3 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREREV3 = 0, PDPREDREV3 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM3 = '' AND PDPPREREV3 > 0
ORDER BY PDPPREREV3, PDPCOD

SELECT PDPCOD, PDPPREREV4 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREREV4 = 0, PDPREDREV4 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM4 = '' AND PDPPREREV4 > 0 
ORDER BY PDPPREREV4, PDPCOD

-- Preco WEB1 2, 3, 4
SELECT PDPCOD, PDPPREWE12 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREWE12 = 0, PDPREDWE12 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM2 = '' AND PDPPREWE12 > 0 
ORDER BY PDPPREWE12, PDPCOD

SELECT PDPCOD, PDPPREWE13 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREWE13 = 0, PDPREDWE13 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM3 = '' AND PDPPREWE13 > 0
ORDER BY PDPPREWE13, PDPCOD

SELECT PDPCOD, PDPPREWE14 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREWE14 = 0, PDPREDWE14 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM4 = '' AND PDPPREWE14 > 0 
ORDER BY PDPPREWE14, PDPCOD

-- Preco WEB2 2, 3, 4
SELECT PDPCOD, PDPPREWE22 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREWE22 = 0, PDPREDWE22 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM2 = '' AND PDPPREWE22 > 0 
ORDER BY PDPPREWE22, PDPCOD

SELECT PDPCOD, PDPPREWE23 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREWE23 = 0, PDPREDWE23 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM3 = '' AND PDPPREWE23 > 0
ORDER BY PDPPREWE23, PDPCOD

SELECT PDPCOD, PDPPREWE24 FROM TBS015 (NOLOCK)
--UPDATE TBS015 SET PDPPREWE24 = 0, PDPREDWE24 = 0
--FROM TBS015
JOIN TBS010
ON PROCOD = PDPCOD AND PROEMPCOD  = PDPPROEMP
WHERE PROUM4 = '' AND PDPPREWE24 > 0 
ORDER BY PDPPREWE24, PDPCOD