-- Preco CORPORATIVO 2, 3, 4
SELECT TDPPROCOD, TDPPRECOR2 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPRECOR2 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM2 = '' AND TDPPRECOR2 > 0 
ORDER BY TDPPRECOR2, TDPPROCOD

SELECT TDPPROCOD, TDPPRECOR3 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPRECOR3 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM3 = '' AND TDPPRECOR3 > 0 
ORDER BY TDPPRECOR3, TDPPROCOD

SELECT TDPPROCOD, TDPPRECOR4 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPRECOR4 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM4 = '' AND TDPPRECOR4 > 0 
ORDER BY TDPPRECOR4, TDPPROCOD

-- Preco LOJA 2, 3, 4
SELECT TDPPROCOD, TDPPRELOJ2 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPRELOJ2 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM2 = '' AND TDPPRELOJ2 > 0 
ORDER BY TDPPRELOJ2, TDPPROCOD

SELECT TDPPROCOD, TDPPRELOJ3 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPRELOJ3 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM3 = '' AND TDPPRELOJ3 > 0
ORDER BY TDPPRELOJ3, TDPPROCOD

SELECT TDPPROCOD, TDPPRELOJ4 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPRELOJ4 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM4 = '' AND TDPPRELOJ4 > 0 
ORDER BY TDPPRELOJ4, TDPPROCOD

-- Preco REVENDA 2, 3, 4
SELECT TDPPROCOD, TDPPREREV2 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREREV2 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM2 = '' AND TDPPREREV2 > 0 
ORDER BY TDPPREREV2, TDPPROCOD

SELECT TDPPROCOD, TDPPREREV3 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREREV3 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM3 = '' AND TDPPREREV3 > 0
ORDER BY TDPPREREV3, TDPPROCOD

SELECT TDPPROCOD, TDPPREREV4 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREREV4 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM4 = '' AND TDPPREREV4 > 0 
ORDER BY TDPPREREV4, TDPPROCOD

-- Preco WEB1 2, 3, 4
SELECT TDPPROCOD, TDPPREWE12 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREWE12 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM2 = '' AND TDPPREWE12 > 0 
ORDER BY TDPPREWE12, TDPPROCOD

SELECT TDPPROCOD, TDPPREWE13 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREWE13 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM3 = '' AND TDPPREWE13 > 0
ORDER BY TDPPREWE13, TDPPROCOD

SELECT TDPPROCOD, TDPPREWE14 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREWE14 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM4 = '' AND TDPPREWE14 > 0 
ORDER BY TDPPREWE14, TDPPROCOD

-- Preco WEB2 2, 3, 4
SELECT TDPPROCOD, TDPPREWE22 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREWE22 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM2 = '' AND TDPPREWE22 > 0 
ORDER BY TDPPREWE22, TDPPROCOD

SELECT TDPPROCOD, TDPPREWE23 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREWE23 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM3 = '' AND TDPPREWE23 > 0
ORDER BY TDPPREWE23, TDPPROCOD

SELECT TDPPROCOD, TDPPREWE24 FROM TBS031 (NOLOCK)
--UPDATE TBS031 SET TDPPREWE24 = 0
--FROM TBS031
JOIN TBS010
ON PROCOD = TDPPROCOD AND PROEMPCOD  = TDPPROEMP
WHERE PROUM4 = '' AND TDPPREWE24 > 0 
ORDER BY TDPPREWE24, TDPPROCOD